{
 "title": "NPU HW MONITORING PROFILE - JTSO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from HW_NPU with key=\"device\""
   },
   {
    "name": "comp_name",
    "label": "HW Component",
    "query": "show tag values from HW_NPU  with key=\"component_name\" where device=~/$rtr/"
   },
   {
    "name": "prop_name",
    "label": "HW Property",
    "query": "show tag values from HW_NPU with key=\"property_name\" where component_name=~/$comp_name/"
   }
  ]
 },
 "panels": [
  { "title": "Router Info & Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Router Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "measurement": "HW_NPU",
     "query": "SELECT last(\"value\") FROM \"HW_NPU\" WHERE (\"device\"::tag=~ /^$rtr$/ and \"component_name\"::tag =~ /^$comp_name$/ AND \"property_name\"::tag =~ /^$prop_name$/) AND $timeFilter and MODEL!='' group by VERSION, MODEL, device",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "component_name::tag", "operator": "=~", "value": "/^$comp_name$/" },
      { "condition": "AND", "key": "property_name::tag", "operator": "=~", "value": "/^$prop_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Chassis Alarms",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "ERRORS",
     "query": "SELECT last(\"alarm_severity\"), last(\"alarm_resource\"), last(\"alarm_time\")/1000000, last(\"alarm_text\") FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) and  $timeFilter GROUP BY \"/system/alarms/alarm/id\"",
     "select": [
      [
       { "params": [ "alarm_severity" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_resource" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_time" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "measurement": "ERRORS",
     "query": "SELECT last(\"alarm_severity_net\"), last(\"alarm_resource_net\"), last(\"alarm_time_net\"), last(\"alarm_text_net\") FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) and  $timeFilter GROUP BY \"alarm_id_net\"",
     "select": [
      [
       { "params": [ "alarm_severity" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_resource" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_time" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "RAW NPU STATISTICS FOR $comp_name - KPI $prop_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "prop_name"
  },
  {
   "title": "History of $prop_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 13 },
   "targets": [
    {
     "alias": "$prop_name",
     "measurement": "HW_NPU",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name::tag", "operator": "=~", "value": "/^$comp_name$/" },
      { "condition": "AND", "key": "property_name::tag", "operator": "=~", "value": "/^$prop_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Value of $prop_name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$prop_name",
     "measurement": "HW_NPU",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name::tag", "operator": "=~", "value": "/^$comp_name$/" },
      { "condition": "AND", "key": "property_name::tag", "operator": "=~", "value": "/^$prop_name$/" }
     ]
    }
   ]
  }
 ]
}