{
 "title": "POWER EXTENSIVE PROFILE - JTS",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "SHORTNAME",
    "label": "Router",
    "query": {
     "query": "label_values(COMPONENTS_used_power, SHORTNAME)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CHASSIS VIEW - $SHORTNAME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "SHORTNAME" },
  {
   "title": "Chassis Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_power_system_capacity{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ambient Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_temperature_ambient{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "{{SHORTNAME}}"
    }
   ]
  },
  {
   "title": "Chassis Power Details",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_power_system_allocated{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Allocated"
    },
    {
     "expr": "COMPONENTS_power_system_capacity{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Capacity"
    },
    {
     "expr": "COMPONENTS_power_system_maximum{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Max."
    },
    {
     "expr": "COMPONENTS_power_system_remaining{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Remaining"
    },
    {
     "expr": "(sum(COMPONENTS_power_zone_0_usage{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}) or vector(0))\n+ (sum(COMPONENTS_power_zone_1_usage{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}) or vector(0))\n+ (sum(COMPONENTS_power_system_usage{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}) or vector(0))",
     "legendFormat": "System Usage"
    }
   ]
  },
  {
   "title": "Chassis Power Details - Zone 0",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_power_zone_0_allocated{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Allocated"
    },
    {
     "expr": "COMPONENTS_power_zone_0_capacity{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Capacity"
    },
    {
     "expr": "COMPONENTS_power_zone_0_maximum{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Maximum"
    },
    {
     "expr": "COMPONENTS_power_zone_0_remaining{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Remaining"
    },
    {
     "expr": "COMPONENTS_power_zone_0_usage{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Usage"
    }
   ]
  },
  {
   "title": "Chassis Power Details - Zone 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_power_zone_1_allocated{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Allocated"
    },
    {
     "expr": "COMPONENTS_power_zone_1_capacity{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Capacity"
    },
    {
     "expr": "COMPONENTS_power_zone_1_maximum{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Maximum"
    },
    {
     "expr": "COMPONENTS_power_zone_1_remaining{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Remaining"
    },
    {
     "expr": "COMPONENTS_power_zone_1_usage{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*chassis.*\"}",
     "legendFormat": "System Usage"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "options": {
    "content": "<h3><center>Overall Traffic Stats</center></h3>\n"
   }
  },
  {
   "title": "Global Traffic in Bps - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(INTERFACES_in_octets_rate{SHORTNAME=~\"$SHORTNAME\"}) * 8",
     "legendFormat": "Total Traffic bps"
    }
   ]
  },
  {
   "title": "Global Traffic in Pps - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(INTERFACES_in_pkts_rate{SHORTNAME=~\"$SHORTNAME\"})",
     "legendFormat": "Total Traffic pps"
    }
   ]
  },
  {
   "title": "Ratio Watts/Gbps - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Watt/Gbps" } },
   "targets": [
    {
     "expr": "(\n  (sum(COMPONENTS_power_zone_0_usage{SHORTNAME=~\"$SHORTNAME\"}) or vector(0))\n  + (sum(COMPONENTS_power_zone_1_usage{SHORTNAME=~\"$SHORTNAME\"}) or vector(0))\n  + (sum(COMPONENTS_power_system_usage{SHORTNAME=~\"$SHORTNAME\"}) or vector(0))\n)\n/\n(\n  (sum(INTERFACES_in_octets_rate{SHORTNAME=~\"$SHORTNAME\", if_unit=\"\"}) or vector(0)) * 8 / 1e9\n  > 0\n)",
     "legendFormat": "Watts/Gbps"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<h3><center>Overall Power Numbers</center></h3>\n"
   }
  },
  {
   "title": "System Usage - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "COMPONENTS_power_system_usage{SHORTNAME=~\"$SHORTNAME\"}",
     "legendFormat": "Power system usage - {{SHORTNAME}}"
    },
    {
     "expr": "COMPONENTS_power_zone_0_usage{SHORTNAME=~\"$SHORTNAME\"}",
     "legendFormat": "Power zone 0 usage - {{SHORTNAME}}"
    },
    {
     "expr": "COMPONENTS_power_zone_1_usage{SHORTNAME=~\"$SHORTNAME\"}",
     "legendFormat": "Power zone 1 usage - {{SHORTNAME}}"
    }
   ]
  },
  {
   "title": "All components power comsuption - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 9, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\".*FPC+[0-9]\"} != 0",
     "legendFormat": "{{component_name}} Used Power"
    },
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*fan.*\"} != 0",
     "legendFormat": "{{component_name}} Used Power"
    },
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*(CB|SIB|SFB|FEB|RE|SCB|SF|Routin).*\"} != 0",
     "legendFormat": "{{component_name}} Used Power"
    }
   ]
  },
  {
   "title": "All components power sharing - $SHORTNAME",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 7, "x": 17, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\".*FPC+[0-9]\"} != 0",
     "legendFormat": "{{component_name}} Used Power"
    },
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*fan.*\"} != 0",
     "legendFormat": "{{component_name}} Used Power"
    },
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*(CB|SIB|SFB|FEB|RE|SCB|SF|Routin).*\"} != 0",
     "legendFormat": "{{component_name}} Used Power"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 47 },
   "options": {
    "content": "<h3><center>Components Temperature</center></h3>\n"
   }
  },
  {
   "title": "All components temperature - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "COMPONENTS_temperature{SHORTNAME=~\"$SHORTNAME\"} != 0",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  { "title": "HW COMPONENT - $SHORTNAME", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }, "repeat": "SHORTNAME" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 67 },
   "options": {
    "content": "<h3><center>FPC/MPC</center></h3>\n"
   }
  },
  {
   "title": "FPC Used Power - $SHORTNAME",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\".*FPC+[0-9]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FPC - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 17, "x": 7, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\".*FPC+[0-9]\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "FPC Max Power - $SHORTNAME",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_power_maximum{SHORTNAME=~\"$SHORTNAME\", component_name=~\".*FPC+[0-9]\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 91 },
   "options": {
    "content": "<h3><center>FAN</center></h3>\n"
   }
  },
  {
   "title": "FAN Tray - $SHORTNAME",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*fan.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FAN Tray - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*fan.*\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "FAN Speed - $SHORTNAME",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_fan_speed{SHORTNAME=~\"$SHORTNAME\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "FAN Speed - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "COMPONENTS_fan_speed{SHORTNAME=~\"$SHORTNAME\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 121 },
   "options": {
    "content": "<h3><center>CB/RE/Fabric</center></h3>\n"
   }
  },
  {
   "title": "CB & Fabric - $SHORTNAME",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*(CB|SIB|SFB|FEB|RE|SCB|SF|Routin).*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CB & Fabric - $SHORTNAME",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*(CB|SIB|SFB|FEB|RE|SCB|SF|Routin).*\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 134 },
   "options": {
    "content": "<h3><center>PSM/PEM</center></h3>\n"
   }
  },
  {
   "title": "PEM - $SHORTNAME",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_output_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*(PSM|PDM|PEM).*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PEM - $SHORTNAME ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 136 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "COMPONENTS_used_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*(PSM|PDM|PEM).*\"}",
     "legendFormat": "{{component_name}} Used Power"
    },
    {
     "expr": "COMPONENTS_output_power{SHORTNAME=~\"$SHORTNAME\", component_name=~\"(?i).*(PSM|PDM|PEM).*\"}",
     "legendFormat": "{{component_name}} Output Power"
    }
   ]
  }
 ]
}