{
 "title": "AGGREGATION POWER EXTENSIVE PROFILE - JTS",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total Power",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(COMPONENTS_power_system_usage) or vector(0))\n+ (sum(COMPONENTS_power_zone_0_usage) or vector(0))\n+ (sum(COMPONENTS_power_zone_1_usage) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(sum(COMPONENTS_power_system_usage) or vector(0))\n+ (sum(COMPONENTS_power_zone_0_usage) or vector(0))\n+ (sum(COMPONENTS_power_zone_1_usage) or vector(0))\n",
     "legendFormat": "Total Power"
    }
   ]
  },
  {
   "title": "Energy consumed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum_over_time((\n  (sum(COMPONENTS_power_system_usage) or vector(0))\n+ (sum(COMPONENTS_power_zone_0_usage) or vector(0))\n+ (sum(COMPONENTS_power_zone_1_usage) or vector(0))\n)[$__range:1m]) / 60",
     "legendFormat": "Energy consumed"
    }
   ]
  },
  {
   "title": "Per Model - Current Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (MODEL) (\n    label_replace(COMPONENTS_power_system_usage, \"m\", \"sys\", \"\", \"\")\n or label_replace(COMPONENTS_power_zone_0_usage, \"m\", \"z0\", \"\", \"\")\n or label_replace(COMPONENTS_power_zone_1_usage, \"m\", \"z1\", \"\", \"\")\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Model power",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum by (MODEL) (\n    label_replace(COMPONENTS_power_system_usage, \"m\", \"sys\", \"\", \"\")\n or label_replace(COMPONENTS_power_zone_0_usage, \"m\", \"z0\", \"\", \"\")\n or label_replace(COMPONENTS_power_zone_1_usage, \"m\", \"z1\", \"\", \"\")\n)",
     "legendFormat": "Total {{MODEL}}"
    }
   ]
  }
 ]
}