{
 "title": "DDOS PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(DDOS_STATS_arrival_rate, SHORTNAME)"
    }
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": {
     "query": "label_values(DDOS_STATS_arrival_rate{SHORTNAME=~\"$rtr\"}, protocol)"
    }
   },
   {
    "name": "sub_proto",
    "label": "Sub Protocol",
    "query": {
     "query": "label_values(DDOS_STATS_arrival_rate{protocol=~\"$proto\"}, sub_protocol)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2><center>All SHORTNAMEs Alarms</center></h2>"
   }
  },
  {
   "title": "Global DDOS_STATS alarms - last 15 minutes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "DDOS_STATS_policer_violation_count{SHORTNAME=~\"$rtr\", policer_state=~\".*VIOLATING.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<h2><center>$rtr per-protocol detail</center></h2>"
   }
  },
  { "title": "$proto - DDOS_STATS PROTECTION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "proto" },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DDOS_STATS_arrival_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=\"aggregate\"})",
     "legendFormat": "received_rate pps"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DDOS_STATS_dropped_aggregate_policer_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=\"aggregate\"})",
     "legendFormat": "drop_rate pps"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DDOS_STATS_arrival_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=\"aggregate\"} - DDOS_STATS_dropped_aggregate_policer_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=\"aggregate\"})",
     "legendFormat": "passed_rate pps"
    }
   ]
  },
  {
   "title": "$proto received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "DDOS_STATS_arrival_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=~\"$sub_proto\"}",
     "legendFormat": "Received $proto ({{sub_protocol}}) Linecard Slot {{_component_id}} "
    }
   ]
  },
  {
   "title": "$proto dropped",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "DDOS_STATS_dropped_aggregate_policer_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=~\"$sub_proto\"}",
     "legendFormat": "Dropped $proto ({{sub_protocol}}) Linecard Slot {{_component_id}}"
    }
   ]
  },
  {
   "title": "$proto punted to RE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "DDOS_STATS_arrival_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=~\"$sub_proto\"} - DDOS_STATS_dropped_aggregate_policer_rate{SHORTNAME=~\"$rtr\", protocol=~\"$proto\", sub_protocol=~\"$sub_proto\"}",
     "legendFormat": "Punted to RE $proto ({{sub_protocol}}) Linecard Slot {{_component_id}}"
    }
   ]
  }
 ]
}