{
 "title": "DDOS PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from DDOS_STATS with key=\"device\""
   },
   {
    "name": "proto",
    "label": "Protocol",
    "query": "show tag values with key=\"protocol\" where device=~/$rtr/"
   },
   {
    "name": "sub_proto",
    "label": "Sub Protocol",
    "query": "show tag values with key=\"sub_protocol\" where protocol=~/$proto/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2><center>All devices Alarms</center></h2>"
   }
  },
  {
   "title": "Global DDOS_STATS alarms - last 15 minutes",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "protocol::tag" ], "type": "tag" },
      { "params": [ "sub_protocol::tag" ], "type": "tag" },
      { "params": [ "_component_id::tag" ], "type": "tag" }
     ],
     "measurement": "DDOS_STATS",
     "query": "SELECT last(\"policer-state\"), \"policer-violation-count\" FROM \"DDOS_STATS\" WHERE time > now()-15m and policer-state=~/.*VIOLATING.*/ GROUP BY \"device\"::tag, \"protocol\"::tag, \"sub_protocol\"::tag, \"_component_id\"::tag",
     "select": [
      [
       { "params": [ "policer-state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
   "options": {
    "content": "<h2><center>$rtr per-protocol detail</center></h2>"
   }
  },
  { "title": "$proto - DDOS_STATS PROTECTION", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }, "repeat": "proto" },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "received_rate pps",
     "query": "select sum(received_rate) from (select (\"arrival-rate\") as received_rate FROM \"DDOS_STATS\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"protocol\"::tag =~ /^$proto$/ and \"sub_protocol\"::tag =~ /^aggregate$/) AND $timeFilter GROUP BY \"_component_id\"::tag fill(0)) group by time(1m)"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "drop_rate pps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(drop_rate) from (select (\"dropped-aggregate-policer_rate\") as drop_rate FROM \"DDOS_STATS\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"protocol\"::tag =~ /^$proto$/ and \"sub_protocol\"::tag =~ /^aggregate$/) AND $timeFilter GROUP BY \"_component_id\"::tag fill(0)) group by time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "passed_rate pps",
     "query": "select sum(punt_rate) from(select ((\"arrival-rate\")-(\"dropped-aggregate-policer_rate\")) as punt_rate FROM \"DDOS_STATS\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"protocol\"::tag =~ /^$proto$/ and \"sub_protocol\"::tag =~ /^aggregate$/) AND $timeFilter GROUP BY \"_component_id\"::tag fill(0)) group by time(1m)"
    }
   ]
  },
  {
   "title": "$proto received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Received $proto ($tag_sub_protocol) Linecard Slot $tag__component_id",
     "groupBy": [
      { "params": [ "_component_id::tag" ], "type": "tag" },
      { "params": [ "sub_protocol::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DDOS_STATS",
     "query": "SELECT \"arrival-rate\" FROM \"DDOS_STATS\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"protocol\"::tag =~ /^$proto$/ AND \"sub_protocol\"::tag =~ /^$sub_proto$/) AND $timeFilter and arrival-rate!=0  GROUP BY \"_component_id\"::tag, \"sub_protocol\"::tag fill(0)",
     "select": [
      [
       { "params": [ "arrival-rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "protocol::tag", "operator": "=~", "value": "/^$proto$/" }
     ]
    }
   ]
  },
  {
   "title": "$proto dropped",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Dropped $proto ($tag_sub_protocol) Linecard Slot $tag__component_id",
     "groupBy": [
      { "params": [ "_component_id::tag" ], "type": "tag" },
      { "params": [ "sub_protocol::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DDOS_STATS",
     "query": "SELECT \"dropped-aggregate-policer_rate\" FROM \"DDOS_STATS\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"protocol\"::tag =~ /^$proto$/ AND \"sub_protocol\"::tag =~ /^$sub_proto$/) AND $timeFilter and dropped-aggregate-policer_rate!=0  GROUP BY \"_component_id\"::tag, \"sub_protocol\"::tag fill(0)",
     "select": [
      [
       { "params": [ "dropped-aggregate-policer_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "protocol::tag", "operator": "=~", "value": "/^$proto$/" }
     ]
    }
   ]
  },
  {
   "title": "$proto punted to RE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Punted to RE $proto ($tag_sub_protocol) Linecard Slot $tag__component_id",
     "groupBy": [
      { "params": [ "_component_id::tag" ], "type": "tag" },
      { "params": [ "sub_protocol::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DDOS_STATS",
     "query": "SELECT \"arrival-rate\" - \"dropped-aggregate-policer_rate\" FROM \"DDOS_STATS\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"protocol\"::tag =~ /^$proto$/ AND \"sub_protocol\"::tag =~ /^$sub_proto$/) AND $timeFilter and arrival-rate!=0 \n GROUP BY \"_component_id\"::tag, \"sub_protocol\"::tag fill(0) ",
     "select": [
      [
       { "params": [ "dropped-aggregate-policer_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "protocol::tag", "operator": "=~", "value": "/^$proto$/" }
     ]
    }
   ]
  }
 ]
}