{
 "title": "ROUTER HEALTH MONITORING PROFILE - JTSO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from HARDWARE with key=\"device\""
   }
  ]
 },
 "panels": [
  {
   "title": "LAST ERRORS (15mins)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ALARM_TYPE",
     "measurement": "ALARMING",
     "query": "SELECT count(\"exception\") FROM \"ALARMING\" WHERE (\"device\" =~ /^$rtr$/) and time > now()-15m  group by \"ALARM_TYPE\" fill(0)",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Current FPC CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_cpu\" FROM \"HARDWARE\" WHERE \"device\" =~ /^$rtr$/ AND \"component_name\" =~ /FPC.*/ AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "FPC0" }
     ]
    }
   ]
  },
  {
   "title": "CHASSIS ALARMS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "/system/alarms/alarm/id" ], "type": "tag" }
     ],
     "measurement": "ERRORS",
     "query": "select count(last) from (SELECT last(\"alarm_text\") FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter GROUP BY \"/system/alarms/alarm/id\")",
     "select": [
      [
       { "params": [ "alarm_text" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Current RE0 CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HARDWARE",
     "query": "SELECT 100 - \"idle_cpu\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine0|RE0/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current RE0 Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HARDWARE",
     "query": "SELECT \"buffer_usage\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine0|RE0/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current FPC Heap Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_memory\" FROM \"HARDWARE\" WHERE \"device\" =~ /^$rtr$/ AND \"component_name\" =~ /FPC.*/ AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "FPC0" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HARDWARE",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current RE1 CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HARDWARE",
     "query": "SELECT 100 - \"idle_cpu\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine1|RE1/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current RE1 Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HARDWARE",
     "query": "SELECT \"buffer_usage\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine1|RE1/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Syslog - OnChange",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LOGS",
     "query": "SELECT * FROM \"LOGS\" WHERE (\"device\"::tag =~ /^$rtr$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "options": {
    "content": "<h2><center>- Alarming -</center><h2>"
   }
  },
  { "title": "Alarming - $rtr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Chassis Alarms",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "measurement": "ERRORS",
     "query": "SELECT last(\"alarm_severity\"), last(\"alarm_resource\"), last(\"alarm_time\")*1000, last(\"alarm_text\") FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) and  $timeFilter GROUP BY \"/system/alarms/alarm/id\"",
     "select": [
      [
       { "params": [ "alarm_severity" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_resource" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_time" ], "type": "field" }
      ],
      [
       { "params": [ "alarm_text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecard Errors",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "alias": "$tag_cmerror_name,COUNT",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "ERRORS",
     "query": "SELECT last( \"cmerror_count\") FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,UPDATE",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "ERRORS",
     "query": "SELECT last( \"cmerror_update\") FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,CLEAR",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "ERRORS",
     "query": "SELECT last( \"cmerror_clear\") FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,SLOT",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "ERRORS",
     "query": "SELECT last( \"cmerror_slot\")+0.1 FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    },
    {
     "alias": "$tag_cmerror_name,DELTA",
     "groupBy": [
      {
       "params": [
        "/junos/chassis/cmerror/counters/name"
       ],
       "type": "tag"
      }
     ],
     "measurement": "ERRORS",
     "query": "SELECT  last( \"cmerror_clear\")-last( \"cmerror_update\")+0.1 FROM \"ERRORS\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter and cmerror_name!='' GROUP BY cmerror_name",
     "select": [
      [
       { "params": [ "cmerror_id" ], "type": "field" }
      ],
      [
       { "params": [ "cmerror_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "RealTime Monitored KPI (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "LINKNAME" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "RealTime Monitored KPI Details (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "LINKNAME" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 43 },
   "options": {
    "content": "<h2><center>- CPU/MEM -</center><h2>"
   }
  },
  {
   "title": "CPU / Memory for Components & Processes - $rtr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "Routing-engine CPU",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU $tag_component_name",
     "measurement": "HARDWARE",
     "query": "SELECT 100-\"idle_cpu\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Routing-Engine Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Mem $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "query": "SELECT \"buffer_usage\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter and component_name=~/.*outing.*|RE.*/ GROUP BY \"component_name\"",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecards CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_cpu\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/) AND component_name=~ /^FPC.*/ and $timeFilter GROUP BY component_name",
     "select": [
      [
       { "params": [ "linecard_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecards Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Heap memory $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_memory\" FROM \"HARDWARE\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter AND component_name=~ /^FPC.*/ GROUP BY \"component_name\"",
     "select": [
      [
       { "params": [ "linecard_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "PROCESS CPU (only >0%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_name - (PID $tag_process_pid)",
     "query": "SELECT \"cpu_utilization\" FROM \"PROCESS\" WHERE (\"device\" =~ /^$rtr$/) and $timeFilter GROUP BY \"name\", \"process_pid\""
    }
   ]
  },
  {
   "title": "CORE Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "PROCESS",
     "query": "SELECT \"cpu_utilization\" FROM \"PROCESS\" WHERE (\"device\" =~ /^$rtr$/) AND \"cpu_utilization\"!=0 and $timeFilter GROUP BY \"name\", \"process_pid\"",
     "select": [
      [
       { "params": [ "core_cpu_instant" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "PROCESS Memory (only >32MB)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_name - (PID $tag_process_pid)",
     "query": "SELECT \"memory_usage\" FROM \"PROCESS\" WHERE (\"device\" =~ /^$rtr$/) AND \"memory_usage\">30000000 and $timeFilter GROUP BY \"name\", \"process_pid\" fill(0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 87 },
   "options": {
    "content": "<h2><center>- Fabric -</center><h2>"
   }
  },
  { "title": "Fabric - $rtr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Fabric Drops PPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Fabric Drops pps $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "select": [
      [
       { "params": [ "fabric_drops_pkts_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "In Fabric PPS ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "In Fabric pps $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "select": [
      [
       { "params": [ "fabric_input_pkts_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Out Fabric PPS ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Out Fabric pps $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "select": [
      [
       { "params": [ "fabric_output_pkts_rate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  }
 ]
}