{
 "title": "OPTICAL MONITORING PROFILE - JTSO",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from OPTIC with key=\"device\""
   },
   {
    "name": "ifname",
    "label": "Phy. Port",
    "query": "show tag values with key=\"if_name\" where device=~/$rtr/"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<H1><center>Global Information</center></H1> \n<H4><i><center>${rtr}</center></i></H4> "
   }
  },
  { "title": "$rtr - Global View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Current CRC ERROR (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "if_name" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "ALARM_TYPE", "operator": "=", "value": "CRC_ERROR" }
     ]
    }
   ]
  },
  {
   "title": "CRC ERROR Details (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "if_name" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "ALARM_TYPE", "operator": "=", "value": "CRC_ERROR" }
     ]
    }
   ]
  },
  {
   "title": "Current Power Levels",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "if_name::tag" ], "type": "tag" },
      { "params": [ "lane_number" ], "type": "tag" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT last(\"rx_dbm\"), last(\"tx_dbm\") FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter GROUP BY \"if_name\", \"lane_number\"",
     "select": [
      [
       { "params": [ "rx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "tx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "current_bias" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Current Optical Alarm",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "if_name::tag" ], "type": "tag" }
     ],
     "measurement": "OPTIC",
     "select": [
      [
       {
        "params": [
         "lane_laser_bias_current_high_alarm"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_bias_current_high_warning"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_bias_current_low_warning"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_output_power_high_alarm"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_output_power_high_warning"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_output_power_low_alarm"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_output_power_low_warning"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_receiver_power_high_alarm"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_receiver_power_low_alarm"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_receiver_power_high_warning"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_receiver_power_low_warning"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       {
        "params": [
         "lane_laser_bias_current_low_alarm"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "lane_rx_loss_of_signal_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "lane_tx_loss_of_signal_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "module_temp_high_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "module_temp_high_warning" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "module_temp_low_alarm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "module_temp_low_warning" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<H1><center>Interface Details</center></H1> "
   }
  },
  { "title": "INTERFACE DETAIL - $ifname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }, "repeat": "ifname" },
  {
   "title": "$ifname - Current RX",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lane $tag_lane_number",
     "groupBy": [
      { "params": [ "lane_number" ], "type": "tag" }
     ],
     "measurement": "OPTIC",
     "select": [
      [
       { "params": [ "rx_dbm" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name::tag", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - Current TX",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Lane $tag_lane_number",
     "groupBy": [
      { "params": [ "lane_number" ], "type": "tag" }
     ],
     "measurement": "OPTIC",
     "select": [
      [
       { "params": [ "tx_dbm" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name::tag", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - TX",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "Lane $tag_lane_number",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"tx_dbm\") as TX FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY lane_number, time(30s) fill(null)",
     "select": [
      [
       { "params": [ "tx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_high_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "tx_low_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    },
    {
     "alias": "WARN",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"tx_high_warn\") as HIGH_WARN, mean(\"tx_low_warn\") as LOW_WARN FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "tx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_high_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "tx_low_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - RX",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "alias": "Lane $tag_lane_number",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"rx_dbm\") as RX FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY lane_number, time(30s) fill(null)",
     "select": [
      [
       { "params": [ "tx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_high_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "tx_low_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    },
    {
     "alias": "WARN",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"rx_high_warn\") as HIGH_WARN, mean(\"rx_low_warn\") as LOW_WARN FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "tx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_high_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "tx_low_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - BIAS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "alias": "Lane $tag_lane_number",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"current_bias\") as BIAS FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY lane_number, time(30s) fill(null)",
     "select": [
      [
       { "params": [ "tx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_high_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "tx_low_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - Module Temperture",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temperture",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"current_temp\") as Temperture  FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY time(30s) fill(null)",
     "select": [
      [
       { "params": [ "tx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_dbm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "rx_high_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "tx_low_warn" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - OSNR",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "OSNR",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"in_block_errors_rate\") as BLOCK_ERROR, mean(\"in_crc_errors_rate\") as CRC_ERROR FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY time(30s) fill(0)",
     "select": [
      [
       { "params": [ "osnr_instant" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - Pre-FEC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Pre-FEC",
     "measurement": "OPTIC",
     "query": "SELECT mean(\"in_block_errors_rate\") as BLOCK_ERROR, mean(\"in_crc_errors_rate\") as CRC_ERROR FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY time(30s) fill(0)",
     "select": [
      [
       { "params": [ "prefec_instant" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - Block/Framing Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "OPTIC",
     "query": "SELECT mean(\"in_block_errors_rate\") as BLOCK_ERROR, mean(\"in_crc_errors_rate\") as CRC_ERROR FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP BY time(30s) fill(0)",
     "select": [
      [
       { "params": [ "in_block_errors_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "in_crc_errors_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "if_name", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "$ifname - Input Frame Size Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "query": "SELECT mean(\"in_frames_64_octets_rate\") as \"64_Bytes\",  mean(\"in_frames_65_127_octets_rate\") as \"65_127_Bytes\", mean(\"in_frames_128_255_octets_rate\") as \"128_255_Bytes\", mean(\"in_frames_256_511_octets_rate\") as \"256_511_Bytes\", mean(\"in_frames_512_1023_octets_rate\") as \"512_1023_Bytes\", mean(\"in_frames_1024_1518_octets_rate\") as \"1024_1518_Bytes\" FROM \"OPTIC\" WHERE (\"device\" =~ /^$rtr$/ AND \"if_name\" =~ /^$ifname$/) AND $timeFilter GROUP by time(30s) "
    }
   ]
  }
 ]
}