{
 "title": "POWER MONITORING PROFILE - JTSO",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Router",
    "query": "show tag values with key=\"device\""
   }
  ]
 },
 "panels": [
  { "title": "CHASSIS VIEW - $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device" },
  {
   "title": "Ambient Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "query": "SELECT last(\"temperature_ambient\") FROM \"POWER\" WHERE device=~/$device/ and component_name=~/(?i)chassis.*/ GROUP BY device"
    }
   ]
  },
  {
   "title": "Chassis Info",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Field tag__component_name",
     "measurement": "POWER",
     "query": "select last(power_system_capacity) from POWER  where device=~/$device/ and component_name=~/(?i)chassis.*/  AND $timeFilter  group by device, VERSION, MODEL, component_name fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=", "value": "rtme-mx-22.englab.juniper.net" }
     ]
    }
   ]
  },
  {
   "title": "Chassis Power Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Field tag__component_name",
     "measurement": "POWER",
     "query": "select last(power_system_allocated), last(power_system_capacity),  last(power_system_maximum), last(power_system_remaining), last(power_system_usage) from POWER  where device=~/$device/ and \n component_name=~/(?i)chassis.*/  AND $timeFilter group by device, component_name fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=", "value": "rtme-mx-22.englab.juniper.net" }
     ]
    }
   ]
  },
  {
   "title": "System Usage - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "$tag_device - $tag_MODEL",
     "measurement": "POWER",
     "query": "SELECT \"power_system_usage\" FROM \"POWER\" WHERE \"device\"=~ /^$device$/  group by device, MODEL",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "All components power comsuption - $device",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT used_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^^FPC+\\d$/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT output_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT used_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)Fan.*/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT used_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)CB|SIB|SFB|RE|SCB|SF|Routin.*/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "All components temperature - $device",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT temperature FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND temperature!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  { "title": "HW COMPONENT - $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 }, "repeat": "device" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "<h3><center>FPC/MPC</center></h3>\n"
   }
  },
  {
   "title": "FPC - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "POWER",
     "query": "SELECT last(used_power), last(power_maximum) FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^^FPC+\\d$/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FPC - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT used_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^^FPC+\\d$/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 70 },
   "options": {
    "content": "<h3><center>FAN</center></h3>\n"
   }
  },
  {
   "title": "FAN Tray - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "POWER",
     "query": "SELECT last(used_power) FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)Fan.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FAN Tray - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT used_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)Fan.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FAN Speed - $device",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "POWER",
     "query": "SELECT last(\"fan_speed\") FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND $timeFilter GROUP BY component_name fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FAN Speed - $device",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "POWER",
     "query": "SELECT (\"fan_speed\") FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND $timeFilter GROUP BY component_name fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "options": {
    "content": "<h3><center>CB/RE/Fabric</center></h3>\n"
   }
  },
  {
   "title": "CB & Fabric - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "POWER",
     "query": "SELECT last(used_power) FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)CB|SIB|SFB|RE|SCB|SF|Routin.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "CB & Fabric - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT used_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)CB|SIB|SFB|RE|SCB|SF|Routin.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 113 },
   "options": {
    "content": "<h3><center>PSM/PEM</center></h3>\n"
   }
  },
  {
   "title": "PEM - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "POWER",
     "query": "SELECT last(output_power) FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "PEM - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "POWER",
     "query": "SELECT output_power FROM \"POWER\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  }
 ]
}