{
 "title": "Admin - Prometheus internal metrics",
 "description": "Almost all internal Prometheus metrics",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(prometheus_build_info, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus Ready",
   "type": "stat",
   "description": "Whether Prometheus startup was fully completed and the server is ready for normal operation.",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_ready{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Configuration Reload",
   "type": "stat",
   "description": "Whether the last configuration reload attempt was successful.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Targets",
   "type": "stat",
   "description": "Number of scrape pool targets.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_targets{instance=\"$instance\"})",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "stat",
   "description": "Total user and system CPU time.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Active Alertmanagers",
   "type": "stat",
   "description": "The number of alertmanagers discovered and active.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Rule Execution",
   "type": "stat",
   "description": "The maximum p99 duration for a rule to execute.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Oldest Value",
   "type": "stat",
   "description": "Oldest timestamp value stored in the database.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(prometheus_tsdb_lowest_timestamp_seconds)-prometheus_tsdb_lowest_timestamp_seconds{instance=\"$instance\"}",
     "legendFormat": "Total Targets"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "stat",
   "description": "Number of open file descriptors.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Log",
   "type": "stat",
   "description": "State of the query log.\nhttps://prometheus.io/docs/guides/query-log/",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_query_log_enabled{instance=\"$instance\"}",
     "legendFormat": "{{ instance }} {{job}}"
    }
   ]
  },
  {
   "title": "Process Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Configuration Reload Time",
   "type": "stat",
   "description": "Last successful configuration reload.",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - prometheus_config_last_reload_success_timestamp_seconds{job=\"prometheus\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Local Storage",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "Resident memory size.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sent Alerts [10m]",
   "type": "stat",
   "description": "Total number of alerts sent.",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_notifications_sent_total{instance=\"$instance\"}[10m]))",
     "legendFormat": "{{alertmanager}}"
    }
   ]
  },
  {
   "title": "Rule Group Evaluation",
   "type": "stat",
   "description": "The maximum p99 duration of rule group evaluations.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "prometheus_rule_group_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
     "legendFormat": "{{ quantile }}"
    }
   ]
  },
  {
   "title": "Active Queries",
   "type": "stat",
   "description": "The current number of queries being executed or waiting.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_engine_queries{instance=\"$instance\"}",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Log Failures",
   "type": "stat",
   "description": "The number of query log failures.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_engine_query_log_failures_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Open"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus CPU Usage %",
     "type": "timeseries",
     "description": "Total user and system CPU time of Prometheus process.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Prometheus RAM Usage",
     "type": "timeseries",
     "description": "Resident memory size of Prometheus process",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent Alerts [10m]",
     "type": "timeseries",
     "description": "Total number of alerts sent in 10 minutes periods.",
     "gridPos": { "h": 10, "w": 15, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(prometheus_notifications_sent_total{instance=\"$instance\"}[10m])",
       "legendFormat": "{{alertmanager}}"
      }
     ]
    },
    {
     "title": "Active Alertmanagers",
     "type": "stat",
     "description": "The number of alertmanagers discovered and active.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_alertmanagers_discovered{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Notification Queue",
     "type": "stat",
     "description": "The number of alert notifications in the queue.",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_notifications_queue_length{instance=\"$instance\"}",
       "legendFormat": "Queue Length"
      }
     ]
    },
    {
     "title": "Alert Errors",
     "type": "stat",
     "description": "Errors sending alert notifications.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_notifications_errors_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Template Expansions",
     "type": "stat",
     "description": "The total number of template text expansions.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_template_text_expansions_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Queue Length"
      }
     ]
    },
    {
     "title": "Template Failures",
     "type": "stat",
     "description": "The total number of template text expansion failures.",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_template_text_expansion_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Queue Length"
      }
     ]
    },
    {
     "title": "Dropped Alerts",
     "type": "stat",
     "description": "Alerts dropped due to errors when sending to Alertmanager.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_notifications_dropped_total{instance=\"$instance\"}[$__range])"
      }
     ]
    }
   ]
  },
  {
   "title": "Head Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "# of Series",
     "type": "timeseries",
     "description": "Total number of series in the head block.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{instance=\"$instance\"}",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Series Churn",
     "type": "timeseries",
     "description": "Total number of series created/removed in the head",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_series_created_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "created"
      },
      {
       "expr": "rate(prometheus_tsdb_head_series_removed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "removed"
      }
     ]
    },
    {
     "title": "Time Bounds",
     "type": "timeseries",
     "description": "Minumum and maximum timestamp of the head block.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "timestamp(prometheus_tsdb_head_max_time_seconds{instance=\"$instance\"})-prometheus_tsdb_head_max_time_seconds{instance=\"$instance\"}",
       "legendFormat": "max"
      },
      {
       "expr": "timestamp(prometheus_tsdb_head_min_time_seconds{instance=\"$instance\"})-prometheus_tsdb_head_min_time_seconds{instance=\"$instance\"}",
       "legendFormat": "min"
      }
     ]
    },
    {
     "title": "Samples Appended",
     "type": "timeseries",
     "description": "Total number of appended samples.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Chunks in Head",
     "type": "timeseries",
     "description": "Total number of chunks in the head block.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{instance=\"$instance\"}",
       "legendFormat": "chunks"
      }
     ]
    },
    {
     "title": "Chunks Churn",
     "type": "timeseries",
     "description": "Total number of chunks created/removed in the head",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_chunks_created_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "created"
      },
      {
       "expr": "rate(prometheus_tsdb_head_chunks_removed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "removed"
      }
     ]
    },
    {
     "title": "Active Appenders",
     "type": "timeseries",
     "description": "Number of currently active appender transactions.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "prometheus_tsdb_head_active_appenders{instance=\"$instance\"}",
       "legendFormat": "active appenders"
      }
     ]
    },
    {
     "title": "Truncations",
     "type": "stat",
     "description": "Total number of head truncations attempted.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_truncations_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    },
    {
     "title": "Failed Truncations",
     "type": "stat",
     "description": "Total number of head truncations that failed.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_truncations_failed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    },
    {
     "title": "Series Not Found",
     "type": "stat",
     "description": "Total number of requests for series that were not found.",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_series_not_found_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    },
    {
     "title": "Samples Out of Order",
     "type": "stat",
     "description": "Total number of appended out of order samples.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_head_out_of_order_samples_appended_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Samples OOO"
      }
     ]
    }
   ]
  },
  {
   "title": "Scrape",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Targets per Job",
     "type": "stat",
     "description": "Current number of targets in this scrape pool.",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_target_scrape_pool_targets{instance=\"$instance\"}",
       "legendFormat": "{{ scrape_job }}"
      }
     ]
    },
    {
     "title": "Actual Intervals between Scrapes (p99)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_target_interval_length_seconds{instance=\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{ interval }}"
      }
     ]
    },
    {
     "title": "Sync Interval",
     "type": "timeseries",
     "description": "Actual interval to sync the scrape pool.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_target_sync_length_seconds{instance=\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Duplicate Rejected",
     "type": "stat",
     "description": "Total number of samples rejected due to duplicate timestamps but different values.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Samples Out of Order",
     "type": "stat",
     "description": "Total number of samples rejected due to not being out of the expected order.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Exemplars Out of Order",
     "type": "stat",
     "description": "Total number of exemplar rejected due to not being out of the expected order.",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_exemplar_out_of_order_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Creation Attempts",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pools_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Reloads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_reloads_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Sample Limit Hits",
     "type": "stat",
     "description": "Total number of scrapes that hit the sample limit and were rejected.",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Label Limit Hits",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_exceeded_label_limits_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Metadata Cache",
     "type": "stat",
     "description": "Metric metadata in the cache for target scraping.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(prometheus_target_metadata_cache_bytes{instance=\"$instance\"})",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Cache Force Flushes",
     "type": "stat",
     "description": "How many times a scrape cache was flushed due to getting big while scrapes are failing.",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_cache_flush_forced_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Samples Out of Bounds",
     "type": "stat",
     "description": "Total number of samples rejected due to timestamp falling outside of the time bounds.",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Target Sync Failure",
     "type": "stat",
     "description": "Total number of target sync failures.",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_sync_failed_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Creation Failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pools_failed_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Reload Failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_reloads_failed_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Body Size Limit Hits",
     "type": "stat",
     "description": "Total number of scrapes that hit the body size limit",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_body_size_limit_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Target Limit Hits",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_target_scrape_pool_exceeded_target_limit_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    },
    {
     "title": "Pool Syncs",
     "type": "stat",
     "description": "Average number syncs executed on scrape pools between all jobs.",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(increase(prometheus_target_scrape_pool_sync_total{instance=\"$instance\"}[$__range]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Duration (p90)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_engine_query_duration_seconds{instance=\"$instance\",quantile=\"0.9\"}",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Query Duration (p99)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_engine_query_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "HTTP Latency (/metrics)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_http_request_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Response Size (/metrics)",
     "type": "heatmap",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_http_response_size_bytes_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Rule Evaluation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rule Execution Time",
     "type": "timeseries",
     "description": "The duration for a rule to execute.",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Rule Group Evaluation Time",
     "type": "timeseries",
     "description": "The duration of rule group evaluations.",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_rule_group_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Rule Groups",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "prometheus_rule_group_rules{instance=\"$instance\"}",
       "legendFormat": "# of rules"
      },
      {
       "expr": "prometheus_rule_group_last_evaluation_samples{instance=\"$instance\"}",
       "legendFormat": "Samples"
      },
      {
       "expr": "prometheus_rule_group_last_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "Last duration"
      },
      {
       "expr": "increase(prometheus_rule_group_iterations_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Iterations"
      },
      {
       "expr": "prometheus_rule_group_interval_seconds{instance=\"$instance\"}",
       "legendFormat": "Interval"
      },
      {
       "expr": "increase(prometheus_rule_group_iterations_missed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Missed"
      },
      {
       "expr": "increase(prometheus_rule_evaluations_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Rule Evaluations"
      },
      {
       "expr": "increase(prometheus_rule_evaluation_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Failed Evaluations"
      }
     ]
    }
   ]
  },
  {
   "title": "Remote Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Samples Rate",
     "type": "timeseries",
     "description": "Samples incoming/sent to Remote Storage",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_in_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "IN"
      },
      {
       "expr": "rate(prometheus_remote_storage_samples_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "OUT"
      }
     ]
    },
    {
     "title": "Remote Sent Rate",
     "type": "timeseries",
     "description": "The total number of bytes of data (not metadata) sent by the queue after compression. Note that when exemplars over remote write is enabled the exemplars included in a remote write request count towards this metric.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(prometheus_remote_storage_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
       "legendFormat": "Sent Bytes"
      }
     ]
    },
    {
     "title": "Send Batch Duration",
     "type": "heatmap",
     "description": "Duration of send calls to the remote storage.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_remote_storage_sent_batch_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Appender Lag",
     "type": "timeseries",
     "description": "Highest timestamp that has come into the remote storage via the Appender interface.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "time() - prometheus_remote_storage_highest_timestamp_in_seconds{instance=\"$instance\"}",
       "legendFormat": "Lag"
      }
     ]
    },
    {
     "title": "Remote Storage Stats",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_bytes_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "increase(prometheus_remote_storage_enqueue_retries_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "__auto"
      },
      {
       "expr": "prometheus_remote_storage_max_samples_per_send{instance=\"$instance\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(prometheus_remote_storage_samples_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(prometheus_remote_storage_samples_dropped_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(prometheus_remote_storage_samples_failed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "rate(prometheus_remote_storage_samples_retried_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "__auto"
      },
      {
       "expr": "prometheus_remote_storage_samples_pending{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Incoming Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Accepted Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "rate(net_conntrack_listener_conn_accepted_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{listener_name}}"
      }
     ]
    },
    {
     "title": "Listener Closed Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "rate(net_conntrack_listener_conn_closed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{listener_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Outgoing Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Established Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_established_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Connection Attempts",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_attempted_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Refused Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"refused\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Closed Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_closed_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Resolution Failures",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"resolution\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Timed-out Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"timeout\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    },
    {
     "title": "Unknown Connection Failures",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "rate(net_conntrack_dialer_conn_failed_total{instance=\"$instance\",reason=\"unknown\"}[$__rate_interval])",
       "legendFormat": "{{dialer_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Discovery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Discovered Scrape Targets",
     "type": "table",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "prometheus_sd_discovered_targets{instance=\"$instance\",name=\"scrape\"}",
       "legendFormat": "{{config}}"
      }
     ]
    },
    {
     "title": "Kubernetes Events: ADD",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_kubernetes_events_total{instance=\"$instance\",event=\"add\"}[$__range])",
       "legendFormat": "{{ role }}"
      }
     ]
    },
    {
     "title": "Kubernetes Events: UPDATE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_kubernetes_events_total{instance=\"$instance\",event=\"update\"}[$__range])",
       "legendFormat": "{{ role }}"
      }
     ]
    },
    {
     "title": "Kubernetes Events: DELETE",
     "type": "stat",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_kubernetes_events_total{instance=\"$instance\",event=\"delete\"}[$__range])",
       "legendFormat": "{{ role }}"
      }
     ]
    },
    {
     "title": "SD Latency (p99)",
     "type": "stat",
     "description": "The duration (99th percentile) of Service Discovery scan/query/fetch requests.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "prometheus_sd_file_scan_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}>0",
       "legendFormat": "File"
      },
      {
       "expr": "prometheus_sd_consul_rpc_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}>0",
       "legendFormat": "Consul {{ call }}/{{ endpoint }}"
      },
      {
       "expr": "prometheus_sd_kuma_fetch_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}>0",
       "legendFormat": "KUMA"
      }
     ]
    },
    {
     "title": "Notify Update Events",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 8, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_updates_total{instance=\"$instance\",name=\"notify\"}[$__range])",
       "legendFormat": "Sent"
      },
      {
       "expr": "increase(prometheus_sd_failed_configs{instance=\"$instance\",name=\"notify\"}[$__range])",
       "legendFormat": "Failed"
      },
      {
       "expr": "increase(prometheus_sd_received_updates_total{instance=\"$instance\",name=\"notify\"}[$__range])",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "Scrape Update Events",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 14, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_updates_total{instance=\"$instance\",name=\"scrape\"}[$__range])",
       "legendFormat": "Sent"
      },
      {
       "expr": "increase(prometheus_sd_failed_configs{instance=\"$instance\",name=\"scrape\"}[$__range])",
       "legendFormat": "Failed"
      },
      {
       "expr": "increase(prometheus_sd_received_updates_total{instance=\"$instance\",name=\"scrape\"}[$__range])",
       "legendFormat": "Received"
      }
     ]
    },
    {
     "title": "DNS-SD Lookups",
     "type": "stat",
     "description": "The number of DNS-SD lookups.",
     "gridPos": { "h": 4, "w": 2, "x": 20, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_dns_lookups_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Open"
      }
     ]
    },
    {
     "title": "ZK Watchers",
     "type": "stat",
     "description": "The current number of Zookeeper-treecache watcher goroutines.",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 36 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_treecache_watcher_goroutines{instance=\"$instance\"}",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "File SD mtime",
     "type": "stat",
     "description": "Modification time of files for File Service Discovery.",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - prometheus_sd_file_mtime_seconds{instance=\"$instance\"}",
       "legendFormat": "{{filename}}"
      }
     ]
    },
    {
     "title": "Service Discovery Failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_sd_azure_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Azure"
      },
      {
       "expr": "increase(prometheus_sd_consul_rpc_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Consul RPC"
      },
      {
       "expr": "increase(prometheus_sd_dns_lookup_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "DNS"
      },
      {
       "expr": "increase(prometheus_sd_file_read_errors_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "File"
      },
      {
       "expr": "increase(prometheus_sd_http_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "HTTP"
      },
      {
       "expr": "increase(prometheus_sd_kuma_fetch_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "KUMA"
      },
      {
       "expr": "increase(prometheus_sd_linode_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Linode"
      },
      {
       "expr": "increase(prometheus_sd_nomad_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Nomad"
      },
      {
       "expr": "increase(prometheus_sd_file_watcher_errors_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "File watcher"
      },
      {
       "expr": "increase(prometheus_treecache_zookeeper_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "ZK"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Page Completion/Flush Rate",
     "type": "timeseries",
     "description": "Page completion/flush rate.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_wal_completed_pages_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "completed"
      },
      {
       "expr": "rate(prometheus_tsdb_wal_page_flushes_total{instance=\"$instance\"}[$__rate_interval])",
       "legendFormat": "flushes"
      }
     ]
    },
    {
     "title": "WAL fsync Duration",
     "type": "timeseries",
     "description": "Duration (p99) of write log fsync.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_wal_fsync_duration_seconds{instance=\"$instance\",quantile=\"0.99\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Truncations",
     "type": "stat",
     "description": "Total number of write log truncations attempted.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_truncations_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Failed Truncations",
     "type": "stat",
     "description": "Total number of write log truncations that failed.",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_truncations_failed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Corruptions",
     "type": "stat",
     "description": "Total number of WAL corruptions.",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_corruptions_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Failed Writes",
     "type": "stat",
     "description": "Total number of write log writes that failed.",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_wal_writes_failed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Watcher Records Failed",
     "type": "stat",
     "description": "Number of records read by the WAL watcher that resulted in an error when decoding.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 32 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(prometheus_wal_watcher_record_decode_failures_total{instance=\"$instance\"}[$__range]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "TSDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Local Storage",
     "type": "timeseries",
     "description": "The number of bytes that are currently used for local storage by all blocks.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "prometheus_tsdb_storage_blocks_bytes{instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Checkpoints Deleted",
     "type": "stat",
     "description": "Total number of checkpoint deletions attempted.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_checkpoint_deletions_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Checkpoints Created",
     "type": "stat",
     "description": "Total number of checkpoint creations attempted.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_checkpoint_creations_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Data Blocks",
     "type": "stat",
     "description": "Number of currently loaded data blocks",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_blocks_loaded{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Vertical Compactions",
     "type": "stat",
     "description": "Total number of compactions done on overlapping blocks.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_vertical_compactions_total{instance=\"$instance\"}[$__range])"
      }
     ]
    },
    {
     "title": "Checkpoint Del Failures",
     "type": "stat",
     "description": "Total number of checkpoint deletions that failed.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_checkpoint_deletions_failed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Checkpoint Create Failures",
     "type": "stat",
     "description": "Total number of checkpoint creations that failed.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_checkpoint_creations_failed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "TSDB Clean Start",
     "type": "stat",
     "description": "Lockfile state from previous execution: CLEAN (no lockfile), REPLACED (lockfile replaced), DISABLED (lockfile disabled).",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_clean_start{instance=\"$instance\"}",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Replay Time",
     "type": "stat",
     "description": "Time taken to replay the data on disk.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_data_replay_duration_seconds{instance=\"$instance\"}",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Symbol Table RAM",
     "type": "stat",
     "description": "Size of symbol table in memory for loaded blocks",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_symbol_table_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "MMap Corruptions",
     "type": "stat",
     "description": "Total number of memory-mapped chunk corruptions.",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_mmap_chunk_corruptions_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Reload Failures",
     "type": "stat",
     "description": "Number of times the database failed to reloadBlocks block data from disk.",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_reloads_failures_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Snapshot Replay Errors",
     "type": "stat",
     "description": "Total number snapshot replays that failed.",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_snapshot_replay_error_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Samples Out of Time",
     "type": "stat",
     "description": "Total number of out of order samples ingestion failed attempts with out of support enabled, but sample outside of time window.",
     "gridPos": { "h": 5, "w": 3, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_too_old_samples_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Time Retention Hits",
     "type": "stat",
     "description": "The number of times that blocks were deleted because the maximum time limit was exceeded.",
     "gridPos": { "h": 5, "w": 3, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_time_retentions_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Size Retention Hits",
     "type": "stat",
     "description": "The number of times that blocks were deleted because the maximum number of bytes was exceeded.",
     "gridPos": { "h": 5, "w": 3, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_size_retentions_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Size Retention Limit",
     "type": "stat",
     "description": "Max number of bytes to be retained in the tsdb blocks.",
     "gridPos": { "h": 5, "w": 3, "x": 21, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_tsdb_retention_limit_bytes{instance=\"$instance\"}",
       "legendFormat": "Total Targets"
      }
     ]
    }
   ]
  },
  {
   "title": "TSDB Compaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compaction Duration",
     "type": "heatmap",
     "description": "Duration of compaction runs",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_compaction_duration_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Compaction Chunk Size",
     "type": "heatmap",
     "description": "Final size of chunks on their first compaction",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_compaction_chunk_size_bytes_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Compaction Chunk Samples",
     "type": "heatmap",
     "description": "Final number of samples on their first compaction",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_compaction_chunk_samples_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Compaction Chunk Time Range",
     "type": "heatmap",
     "description": "Final time range of chunks on their first compaction",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_compaction_chunk_range_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Triggered",
     "type": "stat",
     "description": "Total number of triggered compactions for the partition.",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_compactions_triggered_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Executed",
     "type": "stat",
     "description": "Total number of compactions that were executed for the partition.",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_compactions_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Failed",
     "type": "stat",
     "description": "Total number of compactions that failed for the partition.",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_compactions_failed_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Skipped",
     "type": "stat",
     "description": "Total number of skipped compactions due to disabled auto compaction.",
     "gridPos": { "h": 5, "w": 3, "x": 9, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(prometheus_tsdb_compactions_skipped_total{instance=\"$instance\"}[$__range])",
       "legendFormat": "Total Targets"
      }
     ]
    },
    {
     "title": "Tombstone Cleanup Duration",
     "type": "heatmap",
     "description": "The time taken to recompact blocks to remove tombstones.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "sum(increase(prometheus_tsdb_tombstone_cleanup_seconds_bucket{instance=\"$instance\"}[$__interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}