{
 "title": "TRAFFIC & COS MONITORING PROFILE - JTSO",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values FROM COS with key=\"device\""
   },
   {
    "name": "ifname",
    "label": "Interface",
    "query": "show tag values FROM COS with key=\"LINKNAME\" where device=~/$rtr/"
   },
   { "name": "sample_interval", "label": "Interval", "query": "31s,1m,2m,5m" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2><center>Global KPI - ${rtr}</center><h2>"
   }
  },
  {
   "title": "RealTime CoS Drops (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "LINKNAME" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "query": "SELECT count(\"exception\") FROM \"ALARMING\" WHERE (\"device\" =~ /^$rtr$/) AND ALARM_TYPE=~/RED.*|TAIL.*/ and $timeFilter GROUP BY \"ALARM_TYPE\", \"LINKNAME\", queue_name, queue_id\n",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "PER QUEUE GLOBAL BALANCING",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Q$tag_queue_id",
     "groupBy": [
      { "params": [ "queue_name" ], "type": "tag" }
     ],
     "measurement": "COS",
     "query": "select sum(cos_fw) from (SELECT \"cos_forwarded_octets_rate\"*8 as cos_fw FROM \"COS\" WHERE \"device\" =~ /^$rtr$/  and $timeFilter GROUP BY LINKNAME,  \"queue_id\") group by queue_id",
     "select": [
      [
       { "params": [ "cos_forwarded_octets_rate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Drop Details - Timestamp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "RealTime Monitored CoS Drops Details (TimeFrame) ",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "ALARM_TYPE" ], "type": "tag" },
        { "params": [ "LINKNAME" ], "type": "tag" }
       ],
       "measurement": "ALARMING",
       "query": "SELECT \"exception\" FROM \"ALARMING\" WHERE (\"device\" =~ /^$rtr$/) AND $timeFilter and ALARM_TYPE=~/RED.*|TAIL.*/ GROUP BY \"ALARM_TYPE\", \"LINKNAME\", queue_id, queue_name",
       "select": [
        [
         { "params": [ "exception" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 },
     "options": {
      "content": "<h2><center>Per Interface details</center><h2>"
     }
    }
   ]
  },
  {
   "title": "Traffic and Queues information - $ifname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "ifname",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
     "options": {
      "content": "<h2><center>Traffic info $ifname</center></h2>"
     }
    },
    {
     "title": "Port statistics Bps - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "Input Bps",
       "measurement": "COS",
       "query": "SELECT mean(\"in_octets_rate\")*8  FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) AND $timeFilter group by time($sample_interval)",
       "select": [
        [
         { "params": [ "in_octets_rate" ], "type": "field" }
        ],
        [
         { "params": [ "out_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      },
      {
       "alias": "Output Bps",
       "measurement": "COS",
       "query": "SELECT mean(\"out_octets_rate\")*8 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) AND $timeFilter group by time($sample_interval)",
       "select": [
        [
         { "params": [ "in_octets_rate" ], "type": "field" }
        ],
        [
         { "params": [ "out_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "title": "Port statistics Pps Traffic - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "Input pps",
       "measurement": "COS",
       "query": "SELECT mean(\"in_pkts_rate\")*8  FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) AND $timeFilter group by time($sample_interval)",
       "select": [
        [
         { "params": [ "in_octets_rate" ], "type": "field" }
        ],
        [
         { "params": [ "out_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      },
      {
       "alias": "Output pps",
       "measurement": "COS",
       "query": "SELECT mean(\"out_pkts_rate\")*8 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) AND $timeFilter group by time($sample_interval)",
       "select": [
        [
         { "params": [ "in_octets_rate" ], "type": "field" }
        ],
        [
         { "params": [ "out_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "title": "Drop per queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "RED Drop pps - Q$tag_queue_id",
       "groupBy": [
        { "params": [ "queue_name" ], "type": "tag" }
       ],
       "measurement": "COS",
       "query": "SELECT mean(\"cos_red_dropped_packets_rate\") FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) and  $timeFilter GROUP BY \"queue_id\",  time($sample_interval)",
       "select": [
        [
         { "params": [ "cos_red_dropped_packets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      },
      {
       "alias": "Tail Drop pps - Q$tag_queue_id",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "queue_name" ], "type": "tag" }
       ],
       "measurement": "COS",
       "query": "SELECT mean(\"cos_tail_dropped_packets_rate\") FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) AND $timeFilter GROUP BY time($sample_interval), \"queue_id\"",
       "select": [
        [
         { "params": [ "cos_tail_dropped_packets_rate" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
     "options": {
      "content": "<h2><center>Queues details $ifname</center></h2>"
     }
    },
    {
     "title": "Current Buffer utilization per queue - $ifname",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Q$tag_queue_id",
       "measurement": "COS",
       "query": "SELECT last(\"cos_buffer_cur\")/last(\"cos_buffer_size\")*100 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) and $timeFilter group by queue_id",
       "select": [
        [
         { "params": [ "cos_buffer_usage" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "title": "Peak Buffer utilization per queue - $ifname",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Q$tag_queue_id",
       "measurement": "COS",
       "query": "SELECT last(\"cos_buffer_peak\")/last(\"cos_buffer_size\")*100 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) AND  $timeFilter group by queue_id",
       "select": [
        [
         { "params": [ "cos_buffer_usage" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "title": "Per Queue Traffic balancing - $ifname",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 43 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Q$tag_queue_id",
       "groupBy": [
        { "params": [ "queue_name" ], "type": "tag" }
       ],
       "measurement": "COS",
       "query": "SELECT \"cos_forwarded_octets_rate\"*8 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/)  and $timeFilter GROUP BY \"queue_id\"",
       "select": [
        [
         { "params": [ "cos_forwarded_octets_rate" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Queued Traffic Bps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "Input Bps - Q$tag_queue_id",
       "groupBy": [
        { "params": [ "queue_name" ], "type": "tag" }
       ],
       "measurement": "COS",
       "query": "SELECT mean(\"cos_queued_octets_rate\")*8 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) and $timeFilter GROUP BY \"queue_id\", time($sample_interval)",
       "select": [
        [
         { "params": [ "cos_forwarded_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "title": "Forwarded Traffic Bps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "Input Bps - Q$tag_queue_id",
       "groupBy": [
        { "params": [ "queue_name" ], "type": "tag" }
       ],
       "measurement": "COS",
       "query": "SELECT mean(\"cos_forwarded_octets_rate\")*8 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/)  and $timeFilter GROUP BY \"queue_id\", time($sample_interval)",
       "select": [
        [
         { "params": [ "cos_forwarded_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "title": "Queued Traffic Pps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "Input pps - Q$tag_queue_id",
       "groupBy": [
        { "params": [ "queue_name" ], "type": "tag" }
       ],
       "measurement": "COS",
       "query": "SELECT mean(\"cos_queued_packets_rate\")*8 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/)  and $timeFilter GROUP BY \"queue_id\", time($sample_interval)",
       "select": [
        [
         { "params": [ "cos_forwarded_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    },
    {
     "title": "Forwarded Traffic Pps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "Input pps - Q$tag_queue_id",
       "groupBy": [
        { "params": [ "queue_name" ], "type": "tag" }
       ],
       "measurement": "COS",
       "query": "SELECT mean(\"cos_forwarded_packets_rate\")*8 FROM \"COS\" WHERE (\"device\" =~ /^$rtr$/ AND \"LINKNAME\" =~ /^$ifname$/) AND   $timeFilter GROUP BY \"queue_id\", time($sample_interval)",
       "select": [
        [
         { "params": [ "cos_forwarded_octets_rate" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "LINKNAME", "operator": "=~", "value": "/^$ifname$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}