{
 "title": "ROUTER HEALTH MONITORING PROFILE - JTS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(COMPONENTS_idle_cpu, SHORTNAME)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Router Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "COMPONENTS_idle_cpu{SHORTNAME=~\"$rtr\", component_name=~\".*[eE]0$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LAST ERRORS (15mins)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (ALARM_TYPE) (count_over_time(ALARMING_exception{SHORTNAME=~\"$rtr\"}[15m]))",
     "legendFormat": "{{ALARM_TYPE}}"
    }
   ]
  },
  {
   "title": "Current FPC CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_linecard_cpu{SHORTNAME=~\"$rtr\", component_name=~\"FPC.*\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "CHASSIS ALARMS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (_system_alarms_alarm_id) (JUNOS_ALARMS_alarm_time{SHORTNAME=~\"$rtr\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(count by (alarm_id_net) (JUNOS_ALARMS_alarm_time_net{SHORTNAME=~\"$rtr\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current RE0 CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - COMPONENTS_idle_cpu{SHORTNAME=~\"$rtr\", component_name=~\"Routing Engine0|RE0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current RE0 Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_buffer_usage{SHORTNAME=~\"$rtr\", component_name=~\"Routing Engine0|RE0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current FPC Heap Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_linecard_memory{SHORTNAME=~\"$rtr\", component_name=~\"FPC.*\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "Current RE1 CPU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - COMPONENTS_idle_cpu{SHORTNAME=~\"$rtr\", component_name=~\"Routing Engine1|RE1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current RE1 Mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_buffer_usage{SHORTNAME=~\"$rtr\", component_name=~\"Routing Engine1|RE1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "<h2><center>- Alarming -</center><h2>"
   }
  },
  { "title": "Alarming - $rtr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Chassis Alarms",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "JUNOS_ALARMS_alarm_time_net{SHORTNAME=~\"$rtr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Linecard Errors",
   "type": "yesoreyeram-boomtable-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "JUNOS_CMERROR_cmerror_count{SHORTNAME=~\"$rtr\", cmerror_name!=\"\"}",
     "legendFormat": "{{cmerror_name}},COUNT"
    },
    {
     "expr": "JUNOS_CMERROR_cmerror_update{SHORTNAME=~\"$rtr\", cmerror_name!=\"\"}",
     "legendFormat": "{{cmerror_name}},UPDATE"
    },
    {
     "expr": "JUNOS_CMERROR_cmerror_clear{SHORTNAME=~\"$rtr\", cmerror_name!=\"\"}",
     "legendFormat": "{{cmerror_name}},CLEAR"
    },
    {
     "expr": "JUNOS_CMERROR_cmerror_slot{SHORTNAME=~\"$rtr\", cmerror_name!=\"\"} + 0.1",
     "legendFormat": "{{cmerror_name}},SLOT"
    },
    {
     "expr": "(JUNOS_CMERROR_cmerror_clear{SHORTNAME=~\"$rtr\", cmerror_name!=\"\"} - JUNOS_CMERROR_cmerror_update{SHORTNAME=~\"$rtr\", cmerror_name!=\"\"}) + 0.1",
     "legendFormat": "{{cmerror_name}},DELTA"
    }
   ]
  },
  {
   "title": "RealTime Monitored KPI (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ALARM_TYPE, component_name) (\n  count_over_time(ALARMING_exception{SHORTNAME=~\"$rtr\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RealTime Monitored KPI Details (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALARMING_exception{SHORTNAME=~\"$rtr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<h2><center>- CPU/MEM -</center><h2>"
   }
  },
  {
   "title": "CPU / Memory for Components & Processes - $rtr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "Routing-engine CPU",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (\n  avg by (SHORTNAME, component_name) (\n    avg_over_time(COMPONENTS_idle_cpu{SHORTNAME=~\"$rtr\"}[30s])\n  )\n)",
     "legendFormat": "CPU {{component_name}}"
    }
   ]
  },
  {
   "title": "Routing-Engine Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (component_name) (\n  avg_over_time(COMPONENTS_buffer_usage{SHORTNAME=~\"$rtr\", component_name!~\"FPC.*\"}[31s])\n)",
     "legendFormat": "Mem {{component_name}}"
    }
   ]
  },
  {
   "title": "Linecards CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (component_name) (\n  avg_over_time(COMPONENTS_linecard_cpu{SHORTNAME=~\"$rtr\", component_name=~\"FPC.*\"}[30s])\n)",
     "legendFormat": "CPU {{component_name}}"
    }
   ]
  },
  {
   "title": "Linecards Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (component_name) (\n  avg_over_time(COMPONENTS_linecard_memory{SHORTNAME=~\"$rtr\", component_name=~\"FPC.*\"}[30s])\n)",
     "legendFormat": "Heap memory {{component_name}}"
    }
   ]
  },
  {
   "title": "SYSTEM CPU (only >0%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (process_name, process_pid) (\n  avg_over_time(\n    SYSTEM_process_cpu_utilization{SHORTNAME=~\"$rtr\"}[30s]\n  )\n)",
     "legendFormat": "{{process_name}} - (PID {{process_pid}})"
    }
   ]
  },
  {
   "title": "CORE Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (component_name) (\n  avg_over_time(\n    COMPONENTS_core_cpu_instant{SHORTNAME=~\"$rtr\"}[30s]\n  )\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "PROCESS Memory (only >32MB)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (process_name, process_pid) (\n  avg_over_time(\n    SYSTEM_process_memory_usage{SHORTNAME=~\"$rtr\"}[30s]\n  )\n)",
     "legendFormat": "{{process_name}} - (PID {{process_pid}})"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 82 },
   "options": {
    "content": "<h2><center>- Fabric -</center><h2>"
   }
  },
  { "title": "Fabric - $rtr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Fabric Drops PPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (component_name) (\n  avg_over_time(\n    COMPONENTS_fabric_drops_pkts_rate{SHORTNAME=~\"$rtr\"}[30s]\n  )\n)",
     "legendFormat": "Fabric Drops pps {{component_name}}"
    }
   ]
  },
  {
   "title": "In Fabric PPS ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (component_name) (\n  avg_over_time(\n    COMPONENTS_fabric_input_pkts_rate{SHORTNAME=~\"$rtr\"}[30s]\n  )\n)",
     "legendFormat": "In Fabric pps {{component_name}}"
    }
   ]
  },
  {
   "title": "Out Fabric PPS ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "avg by (component_name) (\n  avg_over_time(\n    COMPONENTS_fabric_output_pkts_rate{SHORTNAME=~\"$rtr\"}[30s]\n  )\n)",
     "legendFormat": "Out Fabric pps {{component_name}}"
    }
   ]
  }
 ]
}