{
 "title": "VMX ROUTER HEALTH MONITORING PROFILE - JTSO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from HARDWARE with key=\"SHORTNAME\""
   }
  ]
 },
 "panels": [
  {
   "title": "Router Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "HW_NPU",
     "query": "SELECT last(\"idle_cpu\") FROM \"HARDWARE\" WHERE \"SHORTNAME\"::tag=~ /^$rtr$/ AND $timeFilter group by VERSION, MODEL, SHORTNAME",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "component_name::tag", "operator": "=~", "value": "/^$comp_name$/" },
      { "condition": "AND", "key": "property_name::tag", "operator": "=~", "value": "/^$prop_name$/" }
     ]
    }
   ]
  },
  {
   "title": "LAST ERRORS (15mins)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_ALARM_TYPE",
     "measurement": "ALARMING",
     "query": "SELECT count(\"exception\") FROM \"ALARMING\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) and time > now()-15m  group by \"ALARM_TYPE\" fill(0)",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Current FPC CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_cpu\" FROM \"HARDWARE\" WHERE \"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /FPC.*/ AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "FPC0" }
     ]
    }
   ]
  },
  {
   "title": "Current RE0 CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HARDWARE",
     "query": "SELECT 100 - \"idle_cpu\" FROM \"HARDWARE\" WHERE (\"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine0|RE0/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current RE0 Mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "HARDWARE",
     "query": "SELECT \"buffer_usage\" FROM \"HARDWARE\" WHERE (\"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /Routing Engine0|RE0/) AND $timeFilter",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "Routing Engine0" }
     ]
    }
   ]
  },
  {
   "title": "Current FPC Heap Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_memory\" FROM \"HARDWARE\" WHERE \"SHORTNAME\" =~ /^$rtr$/ AND \"component_name\" =~ /FPC.*/ AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "component_name", "operator": "=", "value": "FPC0" }
     ]
    }
   ]
  },
  {
   "title": "Syslog - OnChange - last 15 minutes only",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "LOGS",
     "query": "SELECT * FROM \"LOGS\" WHERE (\"SHORTNAME\"::tag =~ /^$rtr$/) AND time>now()-15m and path='/junos/events/event'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME::tag", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<h2><center>- Alarming -</center><h2>"
   }
  },
  { "title": "Alarming - $rtr", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "RealTime Monitored KPI (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "LINKNAME" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "RealTime Monitored KPI Details (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ALARM_TYPE" ], "type": "tag" },
      { "params": [ "LINKNAME" ], "type": "tag" }
     ],
     "measurement": "ALARMING",
     "select": [
      [
       { "params": [ "exception" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<h2><center>- CPU/MEM -</center><h2>"
   }
  },
  {
   "title": "CPU / Memory for Components & Processes - $rtr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "Routing-engine CPU",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU $tag_component_name",
     "measurement": "HARDWARE",
     "query": "SELECT 100-\"idle_cpu\" FROM \"HARDWARE\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter group by component_name",
     "select": [
      [
       { "params": [ "idle_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Routing-Engine Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Mem $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "query": "SELECT \"buffer_usage\" FROM \"HARDWARE\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter and component_name=~/.*outing.*|RE.*/ GROUP BY \"component_name\"",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecards CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "CPU $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_cpu\" FROM \"HARDWARE\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND component_name=~ /^FPC.*/ and $timeFilter GROUP BY component_name",
     "select": [
      [
       { "params": [ "linecard_cpu" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Linecards Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Heap memory $tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "HARDWARE",
     "query": "SELECT \"linecard_memory\" FROM \"HARDWARE\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND $timeFilter AND component_name=~ /^FPC.*/ GROUP BY \"component_name\"",
     "select": [
      [
       { "params": [ "linecard_memory" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "PROCESS CPU (only >0%)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_name - (PID $tag_process_pid)",
     "query": "SELECT \"cpu_utilization\" FROM \"PROCESS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) and $timeFilter GROUP BY \"name\", \"process_pid\""
    }
   ]
  },
  {
   "title": "CORE Utilization",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 7, "x": 7, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "groupBy": [
      { "params": [ "component_name" ], "type": "tag" }
     ],
     "measurement": "PROCESS",
     "query": "SELECT \"cpu_utilization\" FROM \"PROCESS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND \"cpu_utilization\"!=0 and $timeFilter GROUP BY \"name\", \"process_pid\"",
     "select": [
      [
       { "params": [ "core_cpu_instant" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "PROCESS CPU (only >32MB)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_name - (PID $tag_process_pid)",
     "query": "SELECT \"memory_usage\" FROM \"PROCESS\" WHERE (\"SHORTNAME\" =~ /^$rtr$/) AND \"memory_usage\">30000000 and $timeFilter GROUP BY \"name\", \"process_pid\" fill(0)"
    }
   ]
  }
 ]
}