{
 "title": "HW KPI MONITORING PROFILE - JTSO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(HW_NPU_value, SHORTNAME)"
    }
   },
   {
    "name": "comp_name",
    "label": "HW Component",
    "query": {
     "query": "label_values(HW_NPU_value{SHORTNAME=~\"$rtr\"}, component_name)"
    }
   },
   {
    "name": "prop_name",
    "label": "HW Property",
    "query": {
     "query": "label_values(HW_NPU_value{component_name=\"$comp_name\"}, property_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Router Info & Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Router Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "COMPONENTS_idle_cpu{SHORTNAME=~\"$rtr\", component_name=~\".*[eE]0$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis Alarms",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "JUNOS_ALARMS_alarm_time_net{SHORTNAME=~\"$rtr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAW NPU STATISTICS FOR $comp_name - KPI $prop_name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "repeat": "prop_name"
  },
  {
   "title": "History of $prop_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "  avg_over_time(\n   HW_NPU_value{SHORTNAME=~\"$rtr\", component_name=~\"$comp_name\", property_name=~\"$prop_name\"}[30s]\n  )",
     "legendFormat": "$prop_name"
    }
   ]
  },
  {
   "title": "Current Value of $prop_name",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "HW_NPU_value{SHORTNAME=~\"$rtr\", component_name=~\"$comp_name\", property_name=~\"$prop_name\"}",
     "legendFormat": "$prop_name"
    }
   ]
  }
 ]
}