{
 "title": "LOGICAL IF. TRAFFIC MONITORING PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(SUBINTERFACES_unit_in_octets_rate, SHORTNAME)"
    }
   },
   {
    "name": "ifname",
    "label": "Interface",
    "query": {
     "query": "label_values(SUBINTERFACES_unit_in_octets_rate{SHORTNAME=~\"$rtr\"}, LINKNAME)"
    }
   },
   {
    "name": "if_unit",
    "label": "Subinterface",
    "query": {
     "query": "label_values(SUBINTERFACES_unit_in_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\"$ifname\"}, if_unit)"
    }
   },
   { "name": "sample_interval", "label": "Mean", "query": "31s,1m,2m,5m" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2><center>Traffic info $ifname</center></h2>"
   }
  },
  {
   "title": "Global port statistics Bps - $ifname",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"} * 8",
     "legendFormat": "Input Bps"
    },
    {
     "expr": "INTERFACES_out_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"} * 8",
     "legendFormat": "Output Bps"
    }
   ]
  },
  {
   "title": "Unit input traffic sharing - Bps",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUBINTERFACES_unit_in_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=~\"^(?:[0-9]|[1-9][0-9]|[1-9][0-9]{2}|[1-9][0-9]{3}|1[0-5][0-9]{3}|16[0-2][0-9]{2}|163[0-7][0-9]|16380|1638[0-5])$\"} * 8",
     "legendFormat": "Input Bps - {{if_name}}.{{if_unit}}"
    }
   ]
  },
  {
   "title": "Unit output traffic sharing - Bps",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "SUBINTERFACES_unit_out_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=~\"^(?:[0-9]|[1-9][0-9]|[1-9][0-9]{2}|[1-9][0-9]{3}|1[0-5][0-9]{3}|16[0-2][0-9]{2}|163[0-7][0-9]|16380|1638[0-5])$\"} * 8",
     "legendFormat": "Output Bps - {{if_name}}.{{if_unit}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
   "options": {
    "content": "<h2><center>Per Unit Bps/PPS statistics</center><h2>"
   }
  },
  { "title": "Unit: $if_unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "if_unit" },
  {
   "title": "Unit $if_unit - Traffic statistics Bps - Port is $ifname ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "SUBINTERFACES_unit_in_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=~\"$if_unit\"} * 8",
     "legendFormat": "Input Bps - {{if_name}}.{{if_unit}}"
    },
    {
     "expr": "SUBINTERFACES_unit_out_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=~\"$if_unit\"} * 8",
     "legendFormat": "Output Bps - {{if_name}}.{{if_unit}}"
    }
   ]
  },
  {
   "title": "Unit $if_unit - Traffic statistics PPS - Port is $ifname ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "SUBINTERFACES_unit_in_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=~\"$if_unit\"} * 8",
     "legendFormat": "Input PPS - {{if_name}}.{{if_unit}}"
    },
    {
     "expr": "SUBINTERFACES_unit_out_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=~\"$if_unit\"} * 8",
     "legendFormat": "Output PPS - {{if_name}}.{{if_unit}}"
    }
   ]
  }
 ]
}