{
 "title": "PHYSICAL IF. INTERFACES MONITORING PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(INTERFACES_in_octets_rate, SHORTNAME)"
    }
   },
   {
    "name": "ifname",
    "label": "Interface",
    "query": {
     "query": "label_values(INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\"}, LINKNAME)"
    }
   },
   { "name": "sample_interval", "label": "Mean", "query": "31s,1m,2m,5m" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2><center>Global KPI - ${rtr}</center><h2>"
   }
  },
  {
   "title": "RealTime CoS Drops (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ALARM_TYPE, LINKNAME, queue_name, queue_id) (count_over_time(ALARMING_exception{SHORTNAME=~\"$rtr\", ALARM_TYPE=~\"(RED.*|TAIL.*)\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PER QUEUE GLOBAL BALANCING",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (queue_id) (INTERFACES_cos_forwarded_octets_rate{SHORTNAME=~\"$rtr\", if_name=~\"(et|xe|ge).*\", if_unit=\"\"} * 8)",
     "legendFormat": "Q{{queue_id}}"
    }
   ]
  },
  { "title": "Drop Details - Timestamp", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "RealTime Monitored CoS Drops Details (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "ALARMING_exception{SHORTNAME=~\"$rtr\", ALARM_TYPE=~\"(RED.*|TAIL.*)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "<h2><center>All Interfaces Stats</center><h2>"
   }
  },
  { "title": "All Interfaces Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Input All Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\", if_unit=\"\"} * 8",
     "legendFormat": "{{if_name}}"
    }
   ]
  },
  {
   "title": "Output All Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "INTERFACES_out_octets_rate{SHORTNAME=~\"$rtr\", if_unit=\"\"} * 8",
     "legendFormat": "{{if_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "<h2><center>Per Interface details</center><h2>"
   }
  },
  {
   "title": "Traffic and Queues information - $ifname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "repeat": "ifname",
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
     "options": {
      "content": "<h2><center>Traffic info $ifname</center></h2>"
     }
    },
    {
     "title": "Port statistics Bps - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"} * 8",
       "legendFormat": "Input Bps"
      },
      {
       "expr": "INTERFACES_out_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"} * 8",
       "legendFormat": "Output Bps"
      }
     ]
    },
    {
     "title": "Port Global statistics Pps Traffic - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "INTERFACES_in_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}",
       "legendFormat": "Input pps"
      },
      {
       "expr": "INTERFACES_out_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}",
       "legendFormat": "Output pps"
      }
     ]
    },
    {
     "title": "Port statistics Pps Traffic - per Type - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum(INTERFACES_in_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) - (sum(INTERFACES_bcast_in_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) + sum(INTERFACES_mcast_in_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}))",
       "legendFormat": "Unicast Input pps"
      },
      {
       "expr": "sum(INTERFACES_out_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) - (sum(INTERFACES_bcast_out_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) + sum(INTERFACES_mcast_out_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}))",
       "legendFormat": "Unicast Output pps"
      },
      {
       "expr": "INTERFACES_mcast_in_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}",
       "legendFormat": "Mcast Input pps"
      },
      {
       "expr": "INTERFACES_mcast_out_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}",
       "legendFormat": "Mcast Output pps"
      },
      {
       "expr": "INTERFACES_bcast_in_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}",
       "legendFormat": "Bcast Input pps"
      },
      {
       "expr": "INTERFACES_bcast_out_pkts_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}",
       "legendFormat": "Bcast Output pps"
      }
     ]
    },
    {
     "title": "Drop per queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_red_dropped_packets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"})",
       "legendFormat": "RED Drop pps - Q{{queue_id}}"
      },
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_tail_dropped_packets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"})",
       "legendFormat": "Tail Drop pps - Q{{queue_id}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 70 },
     "options": {
      "content": "<h2><center>Queues details $ifname</center></h2>"
     }
    },
    {
     "title": "Current Buffer utilization per queue - $ifname",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_buffer_cur{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) / sum by (queue_id) (INTERFACES_cos_buffer_size{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) * 100",
       "legendFormat": "Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "Peak Buffer utilization per queue - $ifname",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_buffer_peak{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) / sum by (queue_id) (INTERFACES_cos_buffer_size{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) * 100",
       "legendFormat": "Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "Per Queue Traffic balancing - $ifname",
     "type": "piechart",
     "gridPos": { "h": 22, "w": 6, "x": 18, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_forwarded_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"} * 8)",
       "legendFormat": "Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "VOQ System - Max Current Buffer utilization per queue - $ifname",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (queue_id) (JUNOS_QMON_voq_cos_buffer_cur_percent{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\"})",
       "legendFormat": "Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "VOQ System - Max Peak Buffer utilization per queue - $ifname",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by (queue_id) (JUNOS_QMON_voq_cos_buffer_peak_percent{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\"})",
       "legendFormat": "Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "Current Buffer utilization per queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_buffer_cur{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) / sum by (queue_id) (INTERFACES_cos_buffer_size{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) * 100",
       "legendFormat": "Queue Utilization {{queue_id}}"
      },
      {
       "expr": "JUNOS_QMON_voq_cos_buffer_cur_percent{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\"}",
       "legendFormat": "FPC {{_component_id}} PFE {{pfe_index}} VOQ Utilization {{queue_id}}"
      }
     ]
    },
    {
     "title": "Peak Buffer utilization per queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 9, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_buffer_peak{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) / sum by (queue_id) (INTERFACES_cos_buffer_size{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"}) * 100",
       "legendFormat": "Queue Utilization {{queue_id}}"
      },
      {
       "expr": "JUNOS_QMON_voq_cos_buffer_peak_percent{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\"}",
       "legendFormat": "FPC {{_component_id}} PFE {{pfe_index}} VOQ Utilization {{queue_id}}"
      }
     ]
    },
    {
     "title": "Queued Traffic Bps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_queued_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"} * 8)",
       "legendFormat": "Input Bps - Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "Forwarded Traffic Bps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_forwarded_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"} * 8)",
       "legendFormat": "Input Bps - Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "Queued Traffic Pps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_queued_packets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"})",
       "legendFormat": "Input pps - Q{{queue_id}}"
      }
     ]
    },
    {
     "title": "Forwarded Traffic Pps per Queue - $ifname",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (queue_id) (INTERFACES_cos_forwarded_packets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*(${ifname:pipe}).*\", if_unit=\"\"})",
       "legendFormat": "Input pps - Q{{queue_id}}"
      }
     ]
    }
   ]
  }
 ]
}