{
 "title": "ZR/ZR+ OPTICS PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(COMPONENTS_rx_dbm, SHORTNAME)"
    }
   },
   {
    "name": "port",
    "label": "Phy. Port with ZR/ZR+ optic",
    "query": {
     "query": "label_values(COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", OPTIC_DESC=~\".*(400|800).*(ZR|zr).*\", HAS_CHANNEL!=\"yes\"}, LINKNAME)"
    }
   },
   {
    "name": "cage",
    "label": "cage",
    "query": {
     "query": "label_values(COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\"$port\"}, LINKNAME)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<H1><center>ZR/ZR+ Optics</center></H1> "
   }
  },
  { "title": "INTERFACE DETAIL - $port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "port" },
  {
   "title": "$port - Inventory Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$cage.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Optical Alarm",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "COMPONENTS_lane_laser_bias_current_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_bias_current_high_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_bias_current_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_bias_current_low_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_high_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_low_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_high_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_low_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_rx_loss_of_signal_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_tx_loss_of_signal_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_tx_laser_disabled_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Module Temperature Alarms",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "COMPONENTS_module_temp_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_module_temp_high_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_module_temp_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_module_temp_low_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$port - Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_frequency{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"} * 1000000",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "title": "$port - Wavelength",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_wavelength_setpoint{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Wavelenght"
    }
   ]
  },
  {
   "title": "$port - Port Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "INTERFACES_ETH_port_speed{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "port_speed"
    }
   ]
  },
  {
   "title": "$port - Current RX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    }
   ]
  },
  {
   "title": "$port - Current TX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_tx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_tx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    }
   ]
  },
  {
   "title": "$port - RX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_rx_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_rx_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_rx_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    }
   ]
  },
  {
   "title": "$port - RX",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_rx_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_rx_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_rx_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    }
   ]
  },
  {
   "title": "$port - BIAS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "COMPONENTS_current_bias{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_current_bias_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_bias_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_bias_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_bias_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_bias_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    }
   ]
  },
  {
   "title": "$port - Temperture",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "COMPONENTS_current_module_temp{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Module Temperture"
    },
    {
     "expr": "COMPONENTS_temp_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_temp_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_temp_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_temp_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    },
    {
     "expr": "COMPONENTS_current_laser_temp{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}} Laser Temperture"
    }
   ]
  },
  {
   "title": "$port - OSNR",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "COMPONENTS_osnr_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "OSNR"
    }
   ]
  },
  {
   "title": "$port - ESNR",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "COMPONENTS_esnr_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "ESNR"
    }
   ]
  },
  {
   "title": "$port - Pre-FEC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "COMPONENTS_prefec_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Pre-FEC"
    }
   ]
  },
  {
   "title": "$port - FEC Corrected Bits Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "COMPONENTS_fec_corrected_bits_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$cage.*\"}",
     "legendFormat": "FEC Corrected bits rate"
    }
   ]
  },
  {
   "title": "$port - FEC Uncorrected Error Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "targets": [
    {
     "expr": "COMPONENTS_optic_fec_uncorrectable_blocks_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$cage.*\"}",
     "legendFormat": "FEC Uncorrectable error block rate"
    }
   ]
  },
  {
   "title": "$port - Chromatic Dispersion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ps/nm" } },
   "targets": [
    {
     "expr": "COMPONENTS_chroma_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Chroma. Disp. "
    }
   ]
  },
  {
   "title": "$port - Polarization Dependent Loss",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "COMPONENTS_pola_loss_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "PDL"
    }
   ]
  },
  {
   "title": "$port - Second Order Polarization Mode Dispersion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ps^2" } },
   "targets": [
    {
     "expr": "COMPONENTS_2nd_pola_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "SOPMD"
    }
   ]
  },
  {
   "title": "$port - Netconf additionnal info",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "COMPONENTS_transport_optic_cur{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "{{transport_optic_name}}"
    }
   ]
  },
  {
   "title": "$port - Traffic info",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"} * 8",
     "legendFormat": "In bps"
    },
    {
     "expr": "INTERFACES_out_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"} * 8",
     "legendFormat": "Out bps"
    }
   ]
  }
 ]
}