{
 "title": "OPTIC MONITORING PROFILE - JTSO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(COMPONENTS_rx_dbm, SHORTNAME)"
    }
   },
   {
    "name": "port",
    "label": "Phy. Port",
    "query": {
     "query": "label_values(COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", HAS_CHANNEL!=\"yes\"}, LINKNAME)"
    }
   },
   {
    "name": "cage",
    "label": "cage",
    "query": {
     "query": "label_values(COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\"$port\"}, LINKNAME)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<H1><center>OPTIC DASHBOARD</center></H1> \n<H4><i><center>${rtr}</center></i></H4> "
   }
  },
  { "title": "LAYER 2 ERRORS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Current Framing Errors (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (ALARM_TYPE, if_name) (count_over_time(ALARMING_exception{SHORTNAME=~\"$rtr\", ALARM_TYPE=\"CRC_ERROR\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Framing Error Details (TimeFrame) ",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "ALARMING_exception{SHORTNAME=~\"$rtr\", ALARM_TYPE=\"CRC_ERROR\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GLOBAL VIEW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Current Power Levels - non Channelized ports",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", if_name!~\".*[0-9]:.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_tx_dbm{SHORTNAME=~\"$rtr\", if_name!~\".*[0-9]:.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_current_bias{SHORTNAME=~\"$rtr\", if_name!~\".*[0-9]:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Power Levels - Channelized ports",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*[0-9]+:.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_tx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*[0-9]+:.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_current_bias_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*[0-9]+:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Optical Alarm",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "COMPONENTS_lane_laser_bias_current_high_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_bias_current_high_warning{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_bias_current_low_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_bias_current_low_warning{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_high_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_high_warning{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_low_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_output_power_low_warning{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_high_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_high_warning{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_low_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_laser_receiver_power_low_warning{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_rx_loss_of_signal_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_tx_loss_of_signal_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_lane_tx_laser_disabled_alarm{SHORTNAME=~\"$rtr\", lane_number!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "<H1><center>Port Details</center></H1> "
   }
  },
  { "title": "INTERFACE DETAIL - $port", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 }, "repeat": "port" },
  {
   "title": "Inventory Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "COMPONENTS_current_module_temp{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$cage .*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Module Temperature Alarms",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "COMPONENTS_module_temp_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_module_temp_high_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_module_temp_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "COMPONENTS_module_temp_low_warning{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$port - Current RX",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    }
   ]
  },
  {
   "title": "$port - Current TX",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_tx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_tx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    }
   ]
  },
  {
   "title": "$port - RX",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "COMPONENTS_rx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_rx_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_rx_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_rx_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_rx_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    }
   ]
  },
  {
   "title": "$port - TX",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "COMPONENTS_tx_dbm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_tx_dbm_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_tx_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_tx_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_tx_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_tx_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    }
   ]
  },
  {
   "title": "$port - BIAS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "targets": [
    {
     "expr": "COMPONENTS_current_bias{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_current_bias_oc{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\", HAS_CHANNEL!=\"yes\"}",
     "legendFormat": "Lane {{lane_number}}"
    },
    {
     "expr": "COMPONENTS_bias_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_bias_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_bias_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_bias_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    }
   ]
  },
  {
   "title": "$port - Temperture",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "COMPONENTS_current_module_temp{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Module Temperture"
    },
    {
     "expr": "COMPONENTS_temp_high_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_WARN"
    },
    {
     "expr": "COMPONENTS_temp_low_warn{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_WARN"
    },
    {
     "expr": "COMPONENTS_temp_high_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "HIGH_ALARM"
    },
    {
     "expr": "COMPONENTS_temp_low_alarm{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port\"}",
     "legendFormat": "LOW_ALARM"
    },
    {
     "expr": "COMPONENTS_current_laser_temp{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Lane {{lane_number}} Laser Temperture"
    }
   ]
  },
  {
   "title": "$port - Block/Framing Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "INTERFACES_ETH_in_block_errors_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "BLOCK_ERROR"
    },
    {
     "expr": "INTERFACES_ETH_in_crc_errors_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "CRC_ERROR"
    }
   ]
  },
  {
   "title": "$port - FEC Uncorrected Error Block Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "targets": [
    {
     "expr": "COMPONENTS_optic_fec_uncorrectable_blocks_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$cage.*\"}",
     "legendFormat": "FEC Uncorrectable error block rate"
    }
   ]
  },
  {
   "title": "$port - Input Frame Size Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "INTERFACES_ETH_in_frames_64_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "64_Bytes"
    },
    {
     "expr": "INTERFACES_ETH_in_frames_65_127_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "65_127_Bytes"
    },
    {
     "expr": "INTERFACES_ETH_in_frames_128_255_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "128_255_Bytes"
    },
    {
     "expr": "INTERFACES_ETH_in_frames_256_511_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "256_511_Bytes"
    },
    {
     "expr": "INTERFACES_ETH_in_frames_512_1023_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "512_1023_Bytes"
    },
    {
     "expr": "INTERFACES_ETH_in_frames_1024_1518_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "1024_1518_Bytes"
    }
   ]
  },
  {
   "title": "$port - Traffic info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"} * 8",
     "legendFormat": "In bps"
    },
    {
     "expr": "INTERFACES_out_octets_rate{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"} * 8",
     "legendFormat": "Out bps"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 84 },
   "options": {
    "content": "<center><h2>OTN Specific Information</h2></center>"
   }
  },
  {
   "title": "$port - Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_frequency{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"} * 1000000",
     "legendFormat": "Frequency"
    }
   ]
  },
  {
   "title": "$port - Wavelength",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "nm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "COMPONENTS_wavelength_setpoint{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Wavelenght"
    }
   ]
  },
  {
   "title": "$port - Port Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "INTERFACES_ETH_port_speed{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "port_speed"
    }
   ]
  },
  {
   "title": "$port - Carrier Frequency Offset",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "targets": [
    {
     "expr": "COMPONENTS_carrier_off_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Carrier Offset"
    }
   ]
  },
  {
   "title": "$port - Polarization Dependent Loss",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "COMPONENTS_pola_loss_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "PDL"
    }
   ]
  },
  {
   "title": "$port - Second Order Polarization Mode Dispersion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ps^2" } },
   "targets": [
    {
     "expr": "COMPONENTS_2nd_pola_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "SOPMD"
    }
   ]
  },
  {
   "title": "$port - OSNR",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "COMPONENTS_osnr_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "OSNR"
    }
   ]
  },
  {
   "title": "$port - ESNR",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "COMPONENTS_esnr_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "ESNR"
    }
   ]
  },
  {
   "title": "$port - Chromatic Dispersion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ps/nm" } },
   "targets": [
    {
     "expr": "COMPONENTS_chroma_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Chroma. Disp. "
    }
   ]
  },
  {
   "title": "$port - Pre-FEC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "COMPONENTS_prefec_instant{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "Pre-FEC"
    }
   ]
  },
  {
   "title": "$port - Uncorrected FEC blocks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "COMPONENTS_optic_fec_uncorrectable_blocks{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$cage.*\"}",
     "legendFormat": "Uncorrected FEC blocks"
    }
   ]
  },
  {
   "title": "$port - Transport additionnal info",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "COMPONENTS_transport_optic_cur{SHORTNAME=~\"$rtr\", LINKNAME=~\".*$port.*\"}",
     "legendFormat": "{{transport_optic_name}}"
    }
   ]
  }
 ]
}