{
 "title": "BGP MONITORING PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(NETWORK_INSTANCE_BGP_global_as, SHORTNAME)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(NETWORK_INSTANCE_BGP_session_peer_as{SHORTNAME=~\"$rtr\"}, instance_name)"
    }
   },
   {
    "name": "peergroup",
    "label": "Peer Group",
    "query": {
     "query": "label_values(NETWORK_INSTANCE_BGP_group_total_paths{SHORTNAME=~\"$rtr\", instance_name=~\"$instance\"}, peer_group_name)"
    }
   },
   {
    "name": "family",
    "label": "Family",
    "query": {
     "query": "label_values(NETWORK_INSTANCE_BGP_group_safi_total_paths{SHORTNAME=~\"$rtr\", peer_group_name=~\"$peergroup\"}, peer_group_afi_safi_name)"
    }
   },
   {
    "name": "neighbor",
    "label": "Neighbor",
    "query": {
     "query": "label_values(NETWORK_INSTANCE_BGP_safi_received{SHORTNAME=~\"$rtr\", instance_name=~\"$instance\", neighbor_afi_safi_name=~\"$family\"}, neighbor_address)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2><center>Global Info</center></h2>"
   }
  },
  {
   "title": "LOCAL AS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NETWORK_INSTANCE_BGP_global_as{SHORTNAME=~\"$rtr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Prefixes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NETWORK_INSTANCE_BGP_global_total_prefixes{SHORTNAME=~\"$rtr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NETWORK_INSTANCE_BGP_global_total_paths{SHORTNAME=~\"$rtr\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PEER GROUP INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Paths for peer-group $peergroup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "repeat": "peergroup",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "NETWORK_INSTANCE_BGP_group_total_paths{SHORTNAME=~\"$rtr\", instance_name=~\"$instance\", peer_group_name=~\"$peergroup\"}",
     "legendFormat": "{{instance_name}} - {{peer_group_name}}"
    }
   ]
  },
  {
   "title": "Prefixes Stats for peer-group $peergroup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "repeat": "peergroup",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance_name, peer_group_name) (NETWORK_INSTANCE_BGP_group_safi_received{SHORTNAME=~\"$rtr\", instance_name=~\"$instance\", peer_group_name=~\"$peergroup\"})",
     "legendFormat": "Received"
    },
    {
     "expr": "sum by (instance_name, peer_group_name) (NETWORK_INSTANCE_BGP_group_safi_installed{SHORTNAME=~\"$rtr\", instance_name=~\"$instance\", peer_group_name=~\"$peergroup\"})",
     "legendFormat": "Installed"
    },
    {
     "expr": "sum by (instance_name, peer_group_name) (NETWORK_INSTANCE_BGP_group_safi_sent{SHORTNAME=~\"$rtr\", instance_name=~\"$instance\", peer_group_name=~\"$peergroup\"})",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "FAMILIES INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total Paths for family $family",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "repeat": "family",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (peer_group_afi_safi_name) (NETWORK_INSTANCE_BGP_group_safi_total_paths{SHORTNAME=~\"$rtr\", instance_name=~\"$instance\", peer_group_afi_safi_name=~\"$family\"})",
     "legendFormat": "{{peer_group_afi_safi_name}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 },
   "options": {
    "content": "<h2><center>On Change Events</center></h2>"
   }
  },
  {
   "title": "Network Events - OnChange",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 55 },
   "targets": [
    { "expr": "NETWORK_INSTANCE", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NEIGHBOR $neighbor INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "repeat": "neighbor",
   "collapsed": true,
   "panels": [
    {
     "title": "Peer Name",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_session_description{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "DESC"
      }
     ]
    },
    {
     "title": "Peer AS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_session_peer_as{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "PEERAS"
      }
     ]
    },
    {
     "title": "Peer State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_session_state{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "STATE"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 9, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_session_output_queue{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Input Queue"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 11, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_session_output_queue{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Input Queue"
      }
     ]
    },
    {
     "title": "Neighbor $neighbor - current routes per family",
     "type": "bargauge",
     "gridPos": { "h": 23, "w": 11, "x": 13, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_received{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Received - {{neighbor_afi_safi_name}}"
      },
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_received_pre_policy{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"} - NETWORK_INSTANCE_BGP_safi_accepted{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Dropped by policy - {{neighbor_afi_safi_name}}"
      },
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_installed{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Installed - {{neighbor_afi_safi_name}}"
      },
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_sent{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Sent - {{neighbor_afi_safi_name}}"
      }
     ]
    },
    {
     "title": "Max Prefixes config per family",
     "type": "stat",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_max_prefixes{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "{{neighbor_afi_safi_name}}"
      }
     ]
    },
    {
     "title": "Neighbor $neighbor - Routes history",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 13, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_received{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Received routes {{neighbor_afi_safi_name}}"
      },
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_installed{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Installed routes {{neighbor_afi_safi_name}}"
      },
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_sent{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Sent routes {{neighbor_afi_safi_name}}"
      },
      {
       "expr": "NETWORK_INSTANCE_BGP_safi_received_pre_policy{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"} - NETWORK_INSTANCE_BGP_safi_accepted{SHORTNAME=~\"$rtr\", neighbor_address=~\"$neighbor\"}",
       "legendFormat": "Rejected by Policy routes {{neighbor_afi_safi_name}}"
      }
     ]
    }
   ]
  }
 ]
}