{
 "title": "POWER EXTENSIVE PROFILE - JTSO",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Router",
    "query": "show tag values from COMPONENTS with key=\"device\""
   }
  ]
 },
 "panels": [
  { "title": "CHASSIS VIEW - $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device" },
  {
   "title": "Chassis Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Field tag__component_name",
     "measurement": "COMPONENTS",
     "query": "select last(power_system_capacity) from COMPONENTS  where device=~/$device/ and component_name=~/(?i)chassis.*/  AND $timeFilter  group by device, VERSION, MODEL, component_name fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ambient Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "query": "SELECT last(\"temperature_ambient\") FROM \"COMPONENTS\" WHERE device=~/$device/ and component_name=~/(?i)chassis.*/ GROUP BY device"
    }
   ]
  },
  {
   "title": "Chassis Power Details",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Field tag__component_name",
     "measurement": "COMPONENTS",
     "query": "select last(power_system_allocated) as \"System Allocated\" from COMPONENTS where device=~/$device/ and \n component_name=~/(?i)chassis.*/  AND time > now()-5m  group by time(5m), device, component_name fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Field tag__component_name",
     "measurement": "COMPONENTS",
     "query": "select last(power_allocated_zone) as \"System Alloc. Zones\" from (select mean(power_zone_0_allocated) + mean(power_zone_1_allocated) as power_allocated_zone from COMPONENTS where device=~/$device/ and \n component_name=~/(?i)chassis.*/  AND time > now()-5m  group by time(5m), device, component_name fill(0))",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Field tag__component_name",
     "measurement": "COMPONENTS",
     "query": "select last(power_system_capacity) as \"System Capacity\",  last(power_system_maximum) as \"System Max.\", last(power_system_remaining) as \"System Remaining\" from COMPONENTS  where device=~/$device/ and \n component_name=~/(?i)chassis.*/  AND time > now()-5m  group by device, component_name fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Field tag__component_name",
     "measurement": "COMPONENTS",
     "query": "select last(power_usage) as \"System Usage\"  from (select mean(power_zone_0_usage) + mean(power_zone_1_usage) +mean(power_system_usage) as power_usage from COMPONENTS where device=~/$device/ and \n component_name=~/(?i)chassis.*/  AND time > now()-5m group by time(5m), device, component_name fill(0))",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chassis Power Details - Zone 0",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Field tag__component_name",
     "measurement": "COMPONENTS",
     "query": "select last(power_zone_0_allocated), last(power_zone_0_capacity),  last(power_zone_0_maximum), last(power_zone_0_remaining), last(power_zone_0_usage) from COMPONENTS  where device=~/$device/ and \n component_name=~/(?i)chassis.*/  AND $timeFilter group by device, component_name fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Chassis Power Details - Zone 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Field tag__component_name",
     "measurement": "COMPONENTS",
     "query": "select last(power_zone_1_allocated), last(power_zone_1_capacity),  last(power_zone_1_maximum), last(power_zone_1_remaining), last(power_zone_1_usage) from COMPONENTS  where device=~/$device/ and \n component_name=~/(?i)chassis.*/  AND $timeFilter group by device, component_name fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Global Traffic in Bps - $device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "Total Traffic bps",
     "measurement": "COMPONENTS",
     "query": "select sum(all_if) from(SELECT mean(in_octets_rate)*8 as all_if from COMPONENTS WHERE \"device\"=~ /^$device$/  and $timeFilter group by if_name) group by time(1m)",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Global Traffic in Pps - $device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "Total Traffic pps",
     "measurement": "COMPONENTS",
     "query": "select sum(all_if) from(SELECT mean(in_pkts_rate) as all_if from COMPONENTS WHERE \"device\"=~ /^$device$/  and $timeFilter group by if_name) group by time(1m)",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Ratio Watts/Gbps - $device",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Watt/Gbps" } },
   "targets": [
    {
     "alias": "A",
     "measurement": "COMPONENTS",
     "query": "select sum(all_if)/1000000000 from(SELECT mean(in_octets_rate)*8 as all_if from COMPONENTS WHERE \"device\"=~ /^$device$/  and $timeFilter group by if_name) group by time(1m)",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "B",
     "measurement": "COMPONENTS",
     "query": "select (mean(power_zone_0_usage) + mean(power_zone_1_usage) + mean(power_system_usage)) from COMPONENTS where device=~/$device/  and $timeFilter  group by time(1m) fill(0) ",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "System Usage - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "alias": "Power system usage - $tag_device ",
     "measurement": "COMPONENTS",
     "query": "SELECT \"power_system_usage\" FROM \"COMPONENTS\" WHERE \"device\"=~ /^$device$/  group by device, MODEL fill(null)",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Power zone 0 usage - $tag_device ",
     "measurement": "COMPONENTS",
     "query": "SELECT \"power_zone_0_usage\" FROM \"COMPONENTS\" WHERE \"device\"=~ /^$device$/  group by device, MODEL fill(null)",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Power zone 1 usage - $tag_device ",
     "measurement": "COMPONENTS",
     "query": "SELECT \"power_zone_1_usage\" FROM \"COMPONENTS\" WHERE \"device\"=~ /^$device$/  group by device, MODEL fill(null)",
     "select": [
      [
       { "params": [ "power_system_usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "All components power comsuption - $device",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^^FPC+\\d$/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)Fan.*/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)CB.*|SIB|SFB|FEB|.*RE.*|SCB|SF|Routin.*/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Output Power",
     "measurement": "COMPONENTS",
     "query": "SELECT output_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "All components power sharing - $device",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^^FPC+\\d$/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Output Power",
     "measurement": "COMPONENTS",
     "query": "SELECT output_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)Fan.*/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)CB|SIB|SFB|FEB|RE|SCB|SF|Routin.*/ and used_power!= 0 and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "All components temperature - $device",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "COMPONENTS",
     "query": "SELECT temperature FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) and $timeFilter and temperature!=0 group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  { "title": "HW COMPONENT - $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 }, "repeat": "device" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "<h3><center>FPC/MPC</center></h3>\n"
   }
  },
  {
   "title": "FPC - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT last(used_power), last(power_maximum) FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^^FPC+\\d$/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FPC - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^^FPC+\\d$/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 },
   "options": {
    "content": "<h3><center>FAN</center></h3>\n"
   }
  },
  {
   "title": "FAN Tray - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT last(used_power) FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)Fan.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FAN Tray - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)Fan.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FAN Speed - $device",
   "type": "bargauge",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "COMPONENTS",
     "query": "SELECT last(\"fan_speed\") FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND $timeFilter GROUP BY component_name fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "FAN Speed - $device",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "COMPONENTS",
     "query": "SELECT (\"fan_speed\") FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND $timeFilter GROUP BY component_name fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 116 },
   "options": {
    "content": "<h3><center>CB/RE/Fabric</center></h3>\n"
   }
  },
  {
   "title": "CB & Fabric - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "measurement": "COMPONENTS",
     "query": "SELECT last(used_power) FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)CB|SIB|FEB|SFB|RE|SCB|SF|Routin.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "CB & Fabric - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)CB|SIB|SFB|RE|SCB|SF|Routin.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 129 },
   "options": {
    "content": "<h3><center>PSM/PEM</center></h3>\n"
   }
  },
  {
   "title": "PEM - $device",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT last(used_power) FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Output Power",
     "measurement": "COMPONENTS",
     "query": "SELECT last(output_power) FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "PEM - $device",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_component_name Used Power",
     "measurement": "COMPONENTS",
     "query": "SELECT used_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "$tag_component_name Output Power",
     "measurement": "COMPONENTS",
     "query": "SELECT output_power FROM \"COMPONENTS\" WHERE (\"device\"=~ /^$device$/) AND component_name =~/^(?i)PSM|PDM|PEM.*/ and $timeFilter group by component_name, device fill(0)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  }
 ]
}