{
 "title": "BGP MONITORING PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from NETWORK_INSTANCE_BGP with key=\"device\""
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "show tag values with key=\"instance_name\" where device=~/$rtr/"
   },
   {
    "name": "peergroup",
    "label": "Peer Group",
    "query": "show tag values with key=\"peer_group_name\" where device=~/$rtr/ and instance_name=~/$instance/"
   },
   {
    "name": "family",
    "label": "Family",
    "query": "show tag values with key=\"peer_group_afi_safi_name\" where device=~/$rtr/ and peer_group_name=~/$peergroup/"
   },
   {
    "name": "neighbor",
    "label": "Neighbor",
    "query": "show tag values with key=\"neighbor_address\" where device=~/$rtr/ and instance_name=~/$instance/ and neighbor_afi_safi_name=~/$family/ "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h2><center>Global Info</center></h2>"
   }
  },
  {
   "title": "LOCAL AS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "NETWORK_INSTANCE_BGP",
     "select": [
      [
       { "params": [ "global_as" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Prefixes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "NETWORK_INSTANCE_BGP",
     "select": [
      [
       { "params": [ "global_total_prefixes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Paths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "NETWORK_INSTANCE_BGP",
     "select": [
      [
       { "params": [ "global_total_paths" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" }
     ]
    }
   ]
  },
  { "title": "PEER GROUP INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Paths for peer-group $peergroup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "repeat": "peergroup",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_instance_name - $tag_peer_group_name",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "peer_group_name::tag" ], "type": "tag" }
     ],
     "measurement": "NETWORK_INSTANCE_BGP",
     "query": "SELECT \"group_total_paths\" FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"instance_name\"::tag =~ /^$instance$/ AND \"peer_group_name\"::tag =~ /^$peergroup$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag fill(previous)",
     "select": [
      [
       { "params": [ "group_total_paths" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
     ]
    }
   ]
  },
  {
   "title": "Prefixes Stats for peer-group $peergroup",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "repeat": "peergroup",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Received",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "peer_group_name::tag" ], "type": "tag" }
     ],
     "measurement": "NETWORK_INSTANCE_BGP",
     "query": "select sum(mean) from(SELECT mean(\"group_safi_received\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"instance_name\"::tag =~ /^$instance$/ AND \"peer_group_name\"::tag =~ /^$peergroup$/)  AND $timeFilter GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag, \"peer_group_afi_safi_name\"::tag) GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag, time(61s) fill(previous) ",
     "select": [
      [
       { "params": [ "group_safi_received" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
     ]
    },
    {
     "alias": "Installed",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "peer_group_name::tag" ], "type": "tag" }
     ],
     "measurement": "NETWORK_INSTANCE_BGP",
     "query": "select sum(mean) from(SELECT mean(\"group_safi_installed\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"instance_name\"::tag =~ /^$instance$/ AND \"peer_group_name\"::tag =~ /^$peergroup$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag, \"peer_group_afi_safi_name\"::tag) GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag, time(61s) fill(previous)",
     "select": [
      [
       { "params": [ "group_safi_installed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
     ]
    },
    {
     "alias": "Sent",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "peer_group_name::tag" ], "type": "tag" }
     ],
     "measurement": "NETWORK_INSTANCE_BGP",
     "query": "select sum(mean) from(SELECT  mean(\"group_safi_sent\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"instance_name\"::tag =~ /^$instance$/ AND \"peer_group_name\"::tag =~ /^$peergroup$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag, \"peer_group_afi_safi_name\"::tag) GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag, time(61s) fill(previous)",
     "select": [
      [
       { "params": [ "group_safi_sent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
     ]
    }
   ]
  },
  { "title": "FAMILIES INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Paths for family $family",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "repeat": "family",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": " $tag_peer_group_afi_safi_name",
     "groupBy": [
      { "params": [ "instance_name::tag" ], "type": "tag" },
      { "params": [ "peer_group_name::tag" ], "type": "tag" },
      { "params": [ "peer_group_afi_safi_name::tag" ], "type": "tag" }
     ],
     "measurement": "NETWORK_INSTANCE_BGP",
     "query": "select sum(mean) from (SELECT mean(\"group_safi_total_paths\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"instance_name\"::tag =~ /^$instance$/ AND \"peer_group_afi_safi_name\"::tag =~ /^$family$/) AND $timeFilter GROUP BY \"instance_name\"::tag, \"peer_group_name\"::tag, \"peer_group_afi_safi_name\"::tag, time(61s)) GROUP BY \"peer_group_afi_safi_name\"::tag, time(61s) fill(previous)",
     "select": [
      [
       { "params": [ "group_safi_total_paths" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "peer_group_afi_safi_name::tag", "operator": "=~", "value": "/^$family$/" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<h2><center>On Change Events</center></h2>"
   }
  },
  {
   "title": "Network Events - OnChange",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "neighbor_address::tag" ], "type": "tag" }
     ],
     "measurement": "NETWORK_INSTANCE_BGP",
     "query": "SELECT \"session_state\" FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"instance_name\"::tag =~ /^$instance$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) AND $timeFilter GROUP BY \"neighbor_address\"::tag",
     "select": [
      [
       { "params": [ "session_state" ], "type": "field" }
      ],
      [
       { "params": [ "session_description" ], "type": "field" }
      ],
      [
       { "params": [ "session_peer_as" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
     ]
    }
   ]
  },
  {
   "title": "NEIGHBOR $neighbor INFO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "neighbor",
   "collapsed": true,
   "panels": [
    {
     "title": "Peer Name",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "DESC",
       "measurement": "NETWORK_INSTANCE_BGP",
       "select": [
        [
         { "params": [ "session_description" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      }
     ]
    },
    {
     "title": "Peer AS",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "PEERAS",
       "measurement": "NETWORK_INSTANCE_BGP",
       "select": [
        [
         { "params": [ "session_peer_as" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      }
     ]
    },
    {
     "title": "Peer State",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 6, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "STATE",
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT \"session_state\" FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) ",
       "select": [
        [
         { "params": [ "session_state" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 9, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Input Queue",
       "groupBy": [
        { "params": [ "31s" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT mean(\"session_output_queue\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/)   GROUP BY time(31s) fill(previous)",
       "select": [
        [
         { "params": [ "session_output_queue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 11, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Input Queue",
       "groupBy": [
        { "params": [ "31s" ], "type": "time" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT mean(\"session_output_queue\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/)   GROUP BY time(31s) fill(previous)",
       "select": [
        [
         { "params": [ "session_output_queue" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      }
     ]
    },
    {
     "title": "Neighbor $neighbor - current routes per family",
     "type": "bargauge",
     "gridPos": { "h": 23, "w": 11, "x": 13, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "Received - $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "instance_name::tag" ], "type": "tag" },
        { "params": [ "peer_group_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT mean(\"safi_received\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) AND $timeFilter GROUP BY \"neighbor_address\"::tag, \"neighbor_afi_safi_name\"::tag, time(61s) fill(previous) ",
       "select": [
        [
         { "params": [ "safi_received" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
        { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
       ]
      },
      {
       "alias": "Dropped by policy - $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "instance_name::tag" ], "type": "tag" },
        { "params": [ "peer_group_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT mean(\"safi_received_pre_policy\")-mean(\"safi_accepted\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) AND $timeFilter GROUP BY \"neighbor_address\"::tag, \"neighbor_afi_safi_name\"::tag, time(61s) fill(previous) ",
       "select": [
        [
         { "params": [ "safi_received" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
        { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
       ]
      },
      {
       "alias": "Installed - $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "instance_name::tag" ], "type": "tag" },
        { "params": [ "peer_group_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT mean(\"safi_installed\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) AND $timeFilter GROUP BY \"neighbor_address\"::tag, \"neighbor_afi_safi_name\"::tag, time(61s) fill(previous) ",
       "select": [
        [
         { "params": [ "safi_received" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
        { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
       ]
      },
      {
       "alias": "Sent - $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "instance_name::tag" ], "type": "tag" },
        { "params": [ "peer_group_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT mean(\"safi_sent\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) AND $timeFilter GROUP BY \"neighbor_address\"::tag, \"neighbor_afi_safi_name\"::tag, time(61s) fill(previous) ",
       "select": [
        [
         { "params": [ "safi_received" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "instance_name::tag", "operator": "=~", "value": "/^$instance$/" },
        { "condition": "AND", "key": "peer_group_name::tag", "operator": "=~", "value": "/^$peergroup$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Prefixes config per family",
     "type": "stat",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 41 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "neighbor_afi_safi_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT \"session_state\" FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) ",
       "select": [
        [
         { "params": [ "max-prefixes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      }
     ]
    },
    {
     "title": "Neighbor $neighbor - Routes history",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 13, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "Received routes $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "neighbor_afi_safi_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "select": [
        [
         { "params": [ "safi_received" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      },
      {
       "alias": "Installed routes $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "neighbor_afi_safi_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "select": [
        [
         { "params": [ "safi_installed" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      },
      {
       "alias": "Sent routes $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "neighbor_afi_safi_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "select": [
        [
         { "params": [ "safi_sent" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      },
      {
       "alias": "Rejected by Policy routes $tag_neighbor_afi_safi_name",
       "groupBy": [
        { "params": [ "neighbor_afi_safi_name::tag" ], "type": "tag" }
       ],
       "measurement": "NETWORK_INSTANCE_BGP",
       "query": "SELECT (\"safi_received_pre_policy\" -  \"safi_accepted\") FROM \"NETWORK_INSTANCE_BGP\" WHERE (\"device\"::tag =~ /^$rtr$/ AND \"neighbor_address\"::tag =~ /^$neighbor$/) AND $timeFilter GROUP BY \"neighbor_afi_safi_name\"::tag",
       "select": [
        [
         { "params": [ "safi_received_pre_policy" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "device::tag", "operator": "=~", "value": "/^$rtr$/" },
        { "condition": "AND", "key": "neighbor_address::tag", "operator": "=~", "value": "/^$neighbor$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}