apiVersion: 1

datasources:
  - name: JTSDatabase2
    type: prometheus 
    access: proxy
    uid: jtsuid 
    orgId: 1
    version: 1
    editable: true
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      timeInterval: "10s"