{
 "title": "FIREWALL FILTER PROFILE - JTS",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(FIREWALL_fwd_packets_rate, SHORTNAME)"
    }
   },
   {
    "name": "filter",
    "label": "Filter",
    "query": {
     "query": "label_values(FIREWALL_fwd_packets_rate{SHORTNAME=~\"$rtr\"}, fw_name)"
    }
   },
   {
    "name": "cntr",
    "label": "Counter",
    "query": {
     "query": "label_values(FIREWALL_fwd_packets_rate{fw_name=~\"$filter\"}, cntr_name)"
    }
   },
   {
    "name": "plcr",
    "label": "Policer",
    "query": {
     "query": "label_values(FIREWALL_drop_pkts_rate{fw_name=~\"$filter\"}, plcr_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Aggregated counters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Firewall Counters/Policer - PPS VIEW - Aggregation ",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (cntr_name, fw_name) (FIREWALL_fwd_packets_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", cntr_name=~\"$cntr\"})",
     "legendFormat": "Forward PPS {{fw_name}} - {{cntr_name}}"
    },
    {
     "expr": "sum by (plcr_name, fw_name) (FIREWALL_drop_pkts_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", plcr_name=~\"$plcr\"})",
     "legendFormat": "Drop PPS {{fw_name}} - {{plcr_name}}"
    }
   ]
  },
  {
   "title": "Firewall Counters/Policer - BPS VIEW - Aggregation",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (cntr_name, fw_name) (FIREWALL_fwd_bytes_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", cntr_name=~\"$cntr\"}) * 8",
     "legendFormat": "Forward BPS {{fw_name}} - {{cntr_name}}"
    },
    {
     "expr": "sum by (plcr_name, fw_name) (FIREWALL_drop_bytes_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", plcr_name=~\"$plcr\"}) * 8",
     "legendFormat": "Drop BPS {{fw_name}} - {{plcr_name}}"
    }
   ]
  },
  {
   "title": "Per FPC counters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Firewall Counters/Policer - PPS VIEW",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "FIREWALL_fwd_packets_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", cntr_name=~\"$cntr\"}",
       "legendFormat": "Forward PPS {{fw_name}} - {{cntr_name}} - FPC {{_component_id}}"
      },
      {
       "expr": "FIREWALL_drop_pkts_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", plcr_name=~\"$plcr\"}",
       "legendFormat": "Drop PPS {{fw_name}} - {{plcr_name}} - FPC {{_component_id}}"
      }
     ]
    },
    {
     "title": "Firewall Counters/Policer - BPS VIEW",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "FIREWALL_fwd_bytes_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", cntr_name=~\"$cntr\"} * 8",
       "legendFormat": "Forward BPS {{fw_name}} - {{cntr_name}} - FPC {{_component_id}}"
      },
      {
       "expr": "FIREWALL_drop_bytes_rate{SHORTNAME=~\"$rtr\", fw_name=~\"$filter\", plcr_name=~\"$plcr\"} * 8",
       "legendFormat": "Drop BPS {{fw_name}} - {{plcr_name}} - FPC {{_component_id}}"
      }
     ]
    }
   ]
  }
 ]
}