# To enable HTTPS: uncomment these values
#TLS_CERTIFICATE=/etc/chronograf/certs/server.crt
#TLS_PRIVATE_KEY=/etc/chronograf/certs/server.key

INFLUXDB_URL=http://influxdb:8086
KAPACITOR_URL=http://kapacitor:9292
HOST=0.0.0.0
PORT=8888
LOG_LEVEL=info