{
 "title": "SR MPLS PER SID MONITORING PROFILE - JTSO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": "show tag values from SRMPLS_IF_STATS with key=\"SHORTNAME\""
   },
   {
    "name": "ifname",
    "label": "Interface",
    "query": "show tag values from INTERFACES with key=\"if_name\" where SHORTNAME=~/$rtr/"
   },
   {
    "name": "mpls_sid",
    "label": "MPLS SID",
    "query": "show tag values from SRMPLS_SID_STATS with key=\"mpls_label\" where SHORTNAME=~/$rtr/"
   },
   { "name": "interval", "label": "Aggregation Interval", "query": "31s, 1m, 2m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Router Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "measurement": "HW_NPU",
     "query": "SELECT last(\"in_octets_rate\") FROM \"INTERFACES\" WHERE \"SHORTNAME\"::tag=~ /^$rtr$/ AND $timeFilter and MODEL!='' group by VERSION, MODEL, SHORTNAME",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "component_name::tag", "operator": "=~", "value": "/^$comp_name$/" },
      { "condition": "AND", "key": "property_name::tag", "operator": "=~", "value": "/^$prop_name$/" }
     ]
    }
   ]
  },
  {
   "title": "SID Traffic Sharing",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "SID $tag_mpls_label",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRMPLS_IF_STATS",
     "query": "SELECT mean(\"sid_in_pkts_rate\") FROM \"SRMPLS_SID_STATS\" WHERE (\"SHORTNAME\"::tag =~ /^$rtr$/ AND \"mpls_label\"::tag =~ /^.*${mpls_sid:regex}.*$/) AND $timeFilter GROUP BY mpls_label, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "sr_in_octets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "ifl_name::tag", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "SID IN/OUT Bps Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "alias": "SID $tag_mpls_label In Bps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRMPLS_IF_STATS",
     "query": "SELECT mean(\"sid_in_octets_rate\")*8 FROM \"SRMPLS_SID_STATS\" WHERE (\"SHORTNAME\"::tag =~ /^$rtr$/ AND \"mpls_label\"::tag =~ /^.*${mpls_sid:regex}.*$/) AND $timeFilter GROUP BY mpls_label, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "sr_in_octets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "ifl_name::tag", "operator": "=~", "value": "/^$ifname$/" }
     ]
    },
    {
     "alias": "SID $tag_mpls_label Out Bps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRMPLS_IF_STATS",
     "query": "SELECT mean(\"sid_out_octets_rate\")*8 FROM \"SRMPLS_SID_STATS\" WHERE (\"SHORTNAME\"::tag =~ /^$rtr$/ AND \"mpls_label\"::tag =~ /^.*${mpls_sid:regex}.*$/) AND $timeFilter GROUP BY mpls_label, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "sr_in_octets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "ifl_name::tag", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  },
  {
   "title": "SID IN/OUT PPS Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "SID $tag_mpls_label In PPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRMPLS_IF_STATS",
     "query": "SELECT mean(\"sid_in_pkts_rate\") FROM \"SRMPLS_SID_STATS\" WHERE (\"SHORTNAME\"::tag =~ /^$rtr$/ AND \"mpls_label\"::tag =~ /^.*${mpls_sid:regex}.*$/) AND $timeFilter GROUP BY mpls_label, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "sr_in_octets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "ifl_name::tag", "operator": "=~", "value": "/^$ifname$/" }
     ]
    },
    {
     "alias": "SID $tag_mpls_label Out PPS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "SRMPLS_IF_STATS",
     "query": "SELECT mean(\"sid_out_pkts_rate\") FROM \"SRMPLS_SID_STATS\" WHERE (\"SHORTNAME\"::tag =~ /^$rtr$/ AND \"mpls_label\"::tag =~ /^.*${mpls_sid:regex}.*$/) AND $timeFilter GROUP BY mpls_label, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "sr_in_octets_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "SHORTNAME::tag", "operator": "=~", "value": "/^$rtr$/" },
      { "condition": "AND", "key": "ifl_name::tag", "operator": "=~", "value": "/^$ifname$/" }
     ]
    }
   ]
  }
 ]
}