{
 "title": "SR MPLS PER INTF. MONITORING PROFILE - JTSO",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "rtr",
    "label": "Router",
    "query": {
     "query": "label_values(SRMPLS_IF_STATS_sr_in_octets_rate, SHORTNAME)"
    }
   },
   {
    "name": "ifname",
    "label": "Interface",
    "query": {
     "query": "label_values(INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\"}, if_name)"
    }
   },
   { "name": "interval", "label": "Aggregation Interval", "query": "31s, 1m, 2m, 5m" }
  ]
 },
 "panels": [
  { "title": "Router Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Router Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\", MODEL!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SR MPLS Interface Traffic - $ifname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "repeat": "ifname",
   "collapsed": true,
   "panels": [
    {
     "title": "SR IN/OUT Bps Traffic",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "SRMPLS_IF_STATS_sr_in_octets_rate{SHORTNAME=~\"$rtr\", ifl_name=~\".*(${ifname:regex}).*\"} * 8",
       "legendFormat": "{{ifl_name}} In Bps"
      },
      {
       "expr": "SRMPLS_IF_STATS_sr_out_octets_rate{SHORTNAME=~\"$rtr\", ifl_name=~\".*(${ifname:regex}).*\"} * 8",
       "legendFormat": "{{ifl_name}} Out Bps"
      }
     ]
    },
    {
     "title": "SR IN/OUT PPS Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "SRMPLS_IF_STATS_sr_in_pkts_rate{SHORTNAME=~\"$rtr\", ifl_name=~\".*(${ifname:regex}).*\"}",
       "legendFormat": "{{ifl_name}} In PPS"
      },
      {
       "expr": "SRMPLS_IF_STATS_sr_out_pkts_rate{SHORTNAME=~\"$rtr\", ifl_name=~\".*(${ifname:regex}).*\"}",
       "legendFormat": "{{ifl_name}} Out PPS"
      }
     ]
    },
    {
     "title": "In SR MPLS Ratio",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 3, "x": 18, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(SRMPLS_IF_STATS_sr_in_octets_rate{SHORTNAME=~\"$rtr\", ifl_name=~\".*(${ifname:regex}).*\"}) / sum(INTERFACES_in_octets_rate{SHORTNAME=~\"$rtr\", if_name=~\".*(${ifname:regex}).*\"})",
       "legendFormat": "percent_in"
      }
     ]
    },
    {
     "title": "Out SR MPLS Ratio",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 3, "x": 21, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(SRMPLS_IF_STATS_sr_out_octets_rate{SHORTNAME=~\"$rtr\", ifl_name=~\".*(${ifname:regex}).*\"}) / sum(INTERFACES_out_octets_rate{SHORTNAME=~\"$rtr\", if_name=~\".*(${ifname:regex}).*\"})",
       "legendFormat": "percent_out"
      }
     ]
    }
   ]
  }
 ]
}